# Managed for MVN CI/CD reliability and SSH hardening.
LoginGraceTime 30
MaxStartups 20:30:40
PerSourceMaxStartups 10
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin prohibit-password
