#!/bin/bash
set -e

# Configuration
WEB_HOST="mvn-web"
API_HOST="mvn-api"
# PRODUCTION Environment
REMOTE_WEB_DIR="/var/www/user2154318/data/www/mvn.by"
LOCAL_WEB_DIR="./web"

export PUBLIC_SITE_URL="https://mvn.by"

# Ensure build process can access the Local API (Host -> Container Port 8000)
# We use local API for build time data fetching (faster and we have synced DB)
export INTERNAL_API_URL="http://localhost:8000/api/v1"

# Ensure client-side JS points to Production API
export PUBLIC_API_URL="https://api.mvn.by/api/v1"

echo "========================================"
echo "🚀 Deploying WEB (PRODUCTION) to $WEB_HOST..."
echo "Target: $REMOTE_WEB_DIR"
echo "URL: $PUBLIC_SITE_URL"
echo "API: $PUBLIC_API_URL"
echo "========================================"

# 1. Sync media from API (for build/static assets)
echo "🖼️ Syncing media files from $API_HOST..."
# Ensure local media dir exists
mkdir -p "$LOCAL_WEB_DIR/public/media"
rsync -avz "$API_HOST:/opt/air-api/media/" "$LOCAL_WEB_DIR/public/media/"

# 2. Build Frontend Locally
echo "📦 Building Astro project..."
cd "$LOCAL_WEB_DIR"

# Set API URL for the build process (SSG needs access to API)
export INTERNAL_API_URL=$INTERNAL_API_URL
export PUBLIC_API_URL=$PUBLIC_API_URL
export PUBLIC_SITE_URL=$PUBLIC_SITE_URL

npm install
npm run build

if [ $? -ne 0 ]; then
    echo "❌ Build failed! Aborting."
    exit 1
fi
cd ..

# 3. Deploy Static Files
echo "📡 Uploading to $WEB_HOST:$REMOTE_WEB_DIR..."
# Ensure remote directory exists
ssh "$WEB_HOST" "mkdir -p $REMOTE_WEB_DIR"
# Sync dist contents to remote public_html
rsync -avz --delete "$LOCAL_WEB_DIR/dist/" "$WEB_HOST:$REMOTE_WEB_DIR/"

# 4. Robots.txt (Ensure clean robots.txt for production if needed, or use the one generated by build)
# Usually main robots.txt is good.
# echo "🤖 Setting up robots.txt..."

echo "✅ PROD WEB Deployment Complete!"
