version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "4321:4321"
    environment:
      - PUBLIC_API_URL=https://api.mvn.by/api/v1
      - INTERNAL_API_URL=https://api.mvn.by/api/v1
