[pytest]
asyncio_mode = auto
pythonpath = .

testpaths = tests
env =
    DATABASE_URL=postgresql+asyncpg://mvnadmin:v9f2K7mS1a@localhost:5433/air_conditioners_test
    POSTGRES_DB=air_conditioners_test
    POSTGRES_PORT=5433
