"""add_customer_is_archived

Revision ID: 092e5e3c052a
Revises: c1a4d4b2ef29
Create Date: 2026-02-24 13:18:37.502123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092e5e3c052a'
down_revision: Union[str, Sequence[str], None] = 'c1a4d4b2ef29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_index(batch_op.f('ix_customer_is_archived'), ['is_archived'], unique=False)

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('segment_hint',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_is_archived'))
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
