"""Add OrderWorkStage timeline

Revision ID: 42a24b21e39f
Revises: 6424bfd28540
Create Date: 2026-02-25 00:30:47.233091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42a24b21e39f'
down_revision: Union[str, Sequence[str], None] = '6424bfd28540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_work_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('installer_id', sa.Integer(), nullable=True),
    sa.Column('manager_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('installer_report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['installer_id'], ['installers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_work_stage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_work_stage_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_work_stage_status'), ['status'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('standard_install_kit_issued', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_index(batch_op.f('ix_order_equipment_status'), ['equipment_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_equipment_status'))
        batch_op.drop_column('standard_install_kit_issued')
        batch_op.drop_column('equipment_status')

    with op.batch_alter_table('order_work_stage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_work_stage_status'))
        batch_op.drop_index(batch_op.f('ix_order_work_stage_order_id'))

    op.drop_table('order_work_stage')
    # ### end Alembic commands ###
