"""Add ProductImage model and Article.cover_image field

Revision ID: 50a041157d8e
Revises: b01d949da6e4
Create Date: 2026-01-21 18:21:42.422558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a041157d8e'
down_revision: Union[str, Sequence[str], None] = 'b01d949da6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_installation_photo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_image_is_installation_photo'), ['is_installation_photo'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_image_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_image_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_image_is_installation_photo'))

    op.drop_table('product_image')
    # ### end Alembic commands ###
