"""add telegram_id to installer

Revision ID: 525d8f1ff545
Revises: 71eb6e486705
Create Date: 2026-01-18 11:34:55.745369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525d8f1ff545'
down_revision: Union[str, Sequence[str], None] = '71eb6e486705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.BigInteger(), nullable=True))
        batch_op.create_unique_constraint('uq_installer_telegram_id', ['telegram_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_installer_telegram_id', type_='unique')
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
