"""add_rich_fields_to_service

Revision ID: 54bd106a3275
Revises: 88e5255e2d73
Create Date: 2026-01-27 22:36:57.972692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '54bd106a3275'
down_revision: Union[str, Sequence[str], None] = '88e5255e2d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Clear existing data only if slug column doesn't exist (first run)
    service_columns = [col['name'] for col in inspector.get_columns('service')]
    if 'slug' not in service_columns:
        op.execute("DELETE FROM service")
    
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # Check and handle foreign key constraint
    order_service_link_fks = inspector.get_foreign_keys('order_service_link')
    old_fk_exists = any(fk['name'] == 'order_service_link_service_id_fkey' and fk.get('options', {}).get('ondelete') == 'SET NULL' 
                        for fk in order_service_link_fks)
    
    if old_fk_exists:
        with op.batch_alter_table('order_service_link', schema=None) as batch_op:
            batch_op.drop_constraint('order_service_link_service_id_fkey', type_='foreignkey')
            batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'])

    # Add columns to service table only if they don't exist
    service_indexes = [idx['name'] for idx in inspector.get_indexes('service')]
    
    with op.batch_alter_table('service', schema=None) as batch_op:
        if 'slug' not in service_columns:
            batch_op.add_column(sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        if 'category' not in service_columns:
            batch_op.add_column(sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        if 'is_active' not in service_columns:
            batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        if 'image' not in service_columns:
            batch_op.add_column(sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        
        # Create indexes only if they don't exist
        if 'ix_service_category' not in service_indexes:
            batch_op.create_index(batch_op.f('ix_service_category'), ['category'], unique=False)
        if 'ix_service_slug' not in service_indexes:
            batch_op.create_index(batch_op.f('ix_service_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_slug'))
        batch_op.drop_index(batch_op.f('ix_service_category'))
        batch_op.drop_column('image')
        batch_op.drop_column('is_active')
        batch_op.drop_column('category')
        batch_op.drop_column('slug')

    with op.batch_alter_table('order_service_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_service_link_service_id_fkey'), 'service', ['service_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
