"""add_negotiation_fields

Revision ID: 6424bfd28540
Revises: 6f8241e2cd9e
Create Date: 2026-02-24 19:01:44.426017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6424bfd28540'
down_revision: Union[str, Sequence[str], None] = '6f8241e2cd9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('measurement_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('proposal_status', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_measurer_id'), ['measurer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_proposal_status'), ['proposal_status'], unique=False)

    with op.batch_alter_table('order_product_link', schema=None) as batch_op:
        batch_op.alter_column('is_installation_included',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('installation_price',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('installation_details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='installation_details::json')

    with op.batch_alter_table('order_service_link', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_service_link', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('order_product_link', schema=None) as batch_op:
        batch_op.alter_column('installation_details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('installation_price',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_installation_included',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_proposal_status'))
        batch_op.drop_index(batch_op.f('ix_order_measurer_id'))
        batch_op.drop_column('proposal_status')
        batch_op.drop_column('measurement_result')
        batch_op.drop_column('measurer_id')

    # ### end Alembic commands ###
