"""add_payment_model

Revision ID: 6f8241e2cd9e
Revises: 73cde24a86a8
Create Date: 2026-02-24 17:04:20.369065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f8241e2cd9e'
down_revision: Union[str, Sequence[str], None] = '73cde24a86a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_type'), ['type'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_payments', sa.Float(), nullable=False, server_default=sa.text('0.0')))
        batch_op.add_column(sa.Column('balance_due', sa.Float(), nullable=False, server_default=sa.text('0.0')))
        
    op.execute("""
        INSERT INTO payment (order_id, amount, date, type, created_at, updated_at)
        SELECT id, COALESCE(total_amount, 0.0), NOW(), 'postpayment', NOW(), NOW()
        FROM "order"
        WHERE is_paid = TRUE
    """)
    op.execute("""
        UPDATE "order"
        SET total_payments = COALESCE(total_amount, 0.0), balance_due = 0.0
        WHERE is_paid = TRUE
    """)
    op.execute("""
        UPDATE "order"
        SET total_payments = 0.0, balance_due = COALESCE(total_amount, 0.0)
        WHERE is_paid = FALSE OR is_paid IS NULL
    """)

    # ### end Alembic commands ###




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('balance_due')
        batch_op.drop_column('total_payments')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_type'))
        batch_op.drop_index(batch_op.f('ix_payment_order_id'))

    op.drop_table('payment')
    # ### end Alembic commands ###
