"""order_status_3_stages

Revision ID: 73cde24a86a8
Revises: 092e5e3c052a
Create Date: 2026-02-24 15:51:15.068471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73cde24a86a8'
down_revision: Union[str, Sequence[str], None] = '092e5e3c052a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closing_result', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_on_hold', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('on_hold_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('measurement_required', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('measurement_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proposal_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('works_plan', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_closing_result'), ['closing_result'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_is_on_hold'), ['is_on_hold'], unique=False)
        # Rename assessment_date → measurement_date
        batch_op.drop_column('assessment_date')

    # --- Data migration: map old statuses to new 3-stage model ---
    op.execute("""
        UPDATE "order"
        SET status = 'negotiation'
        WHERE status IN ('assessment', 'proposal', 'deferred', 'won_deposit')
    """)
    op.execute("""
        UPDATE "order"
        SET status = 'execution'
        WHERE status = 'installation'
    """)
    op.execute("""
        UPDATE "order"
        SET status = 'closed', closing_result = 'won'
        WHERE status = 'completed'
    """)
    op.execute("""
        UPDATE "order"
        SET status = 'closed', closing_result = 'lost'
        WHERE status = 'canceled'
    """)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_service_link', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('order_product_link', schema=None) as batch_op:
        batch_op.alter_column('installation_details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('installation_price',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_installation_included',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_order_is_on_hold'))
        batch_op.drop_index(batch_op.f('ix_order_closing_result'))
        batch_op.drop_column('works_plan')
        batch_op.drop_column('proposal_sent_at')
        batch_op.drop_column('measurement_date')
        batch_op.drop_column('measurement_required')
        batch_op.drop_column('on_hold_reason')
        batch_op.drop_column('is_on_hold')
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('closing_result')

    # ### end Alembic commands ###
