"""Add CRM models

Revision ID: a55c3fc61562
Revises: 
Create Date: 2026-01-17 01:28:20.663668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a55c3fc61562'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_installers',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('installer_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agreed_pay', sa.Float(), nullable=False),
    sa.Column('is_paid_to_installer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['installer_id'], ['installers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'installer_id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('main_image',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_index(batch_op.f('idx_article_slug'))
        batch_op.create_index(batch_op.f('ix_article_slug'), ['slug'], unique=True)
        batch_op.drop_column('image_url')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('individual', 'company', name='customertype'),
               nullable=False,
               existing_server_default=sa.text("'individual'"))
        batch_op.alter_column('full_legal_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('inn',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('kpp',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('legal_address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('actual_address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('bic',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('iban',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('signer_position',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'Генерального директора'"))
        batch_op.alter_column('signer_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('acting_basis',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'Устава'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('technical_meta', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=False, server_default=sa.text("0.0")))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False, server_default=sa.text("0.0")))
        batch_op.add_column(sa.Column('margin', sa.Float(), nullable=False, server_default=sa.text("0.0")))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('assessment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('installation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('delivery_address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('NEW_LEAD', 'ASSESSMENT', 'PROPOSAL', 'NEGOTIATION', 'DEFERRED', 'WON_DEPOSIT', 'INSTALLATION', 'COMPLETED', 'CANCELED', name='orderstatus'),
               nullable=False,
               existing_server_default=sa.text("'new'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)

    with op.batch_alter_table('order_product_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False, server_default=sa.text("0")))

    with op.batch_alter_table('order_service_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False, server_default=sa.text("0")))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('is_inverter',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_product_is_inverter'), ['is_inverter'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_power_cooling'), ['power_cooling'], unique=False)
        batch_op.drop_column('categories')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_slug'))
        batch_op.create_index(batch_op.f('ix_tag_slug'), ['slug'], unique=True)

    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'secondary'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'secondary'"))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_slug'))
        batch_op.create_index(batch_op.f('ix_tag_slug'), ['slug'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sqlite.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_product_power_cooling'))
        batch_op.drop_index(batch_op.f('ix_product_is_inverter'))
        batch_op.alter_column('is_inverter',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('order_service_link', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('order_product_link', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('NEW_LEAD', 'ASSESSMENT', 'PROPOSAL', 'NEGOTIATION', 'DEFERRED', 'WON_DEPOSIT', 'INSTALLATION', 'COMPLETED', 'CANCELED', name='orderstatus'),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'new'"))
        batch_op.alter_column('delivery_address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('closed_at')
        batch_op.drop_column('installation_date')
        batch_op.drop_column('assessment_date')
        batch_op.drop_column('is_paid')
        batch_op.drop_column('margin')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('technical_meta')
        batch_op.drop_column('title')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('acting_basis',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Устава'"))
        batch_op.alter_column('signer_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('signer_position',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Генерального директора'"))
        batch_op.alter_column('iban',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bic',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('actual_address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('legal_address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('kpp',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('inn',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('full_legal_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Enum('individual', 'company', name='customertype'),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'individual'"))
        batch_op.alter_column('email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_article_slug'))
        batch_op.create_index(batch_op.f('idx_article_slug'), ['slug'], unique=1)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('main_image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('slug',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)

    op.drop_table('order_installers')
    op.drop_table('installers')
    # ### end Alembic commands ###
