"""add payment currency

Revision ID: a6fedc10e8ba
Revises: e78bad921d0d
Create Date: 2026-03-11 21:31:31.292618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6fedc10e8ba'
down_revision: Union[str, Sequence[str], None] = 'e78bad921d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="BYN"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
