"""add_slug_to_product

Revision ID: b01d949da6e4
Revises: dec193022d0d
Create Date: 2026-01-20 20:42:30.692576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b01d949da6e4'
down_revision: Union[str, Sequence[str], None] = 'dec193022d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add slug column as nullable
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Step 2: Populate slug values from title using Python slugify
    import slugify as slugify_lib
    from sqlalchemy import text
    
    connection = op.get_bind()
    products = connection.execute(text("SELECT id, title FROM product")).fetchall()
    
    for product_id, title in products:
        slug = slugify_lib.slugify(title, separator='-')
        # Ensure uniqueness by appending id if needed
        slug_with_id = f"{slug}-{product_id}"
        connection.execute(
            text("UPDATE product SET slug = :slug WHERE id = :id"),
            {"slug": slug_with_id, "id": product_id}
        )
    
    # Step 3: Make slug NOT NULL and add unique index
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)
        batch_op.create_index(batch_op.f('ix_product_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
