"""fix_missing_columns_after_restore

Revision ID: c6fb1dd4d4e0
Revises: f37e06766b7c
Create Date: 2026-01-25 11:48:44.101390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6fb1dd4d4e0'
down_revision: Union[str, Sequence[str], None] = 'f37e06766b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # Step 1: Add as nullable
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Step 2: Populate
    import slugify as slugify_lib
    from sqlalchemy import text
    
    connection = op.get_bind()
    products = connection.execute(text("SELECT id, title FROM product")).fetchall()
    
    for product_id, title in products:
        slug = slugify_lib.slugify(title, separator='-')
        # Ensure uniqueness by appending id if needed
        slug_with_id = f"{slug}-{product_id}"
        connection.execute(
            text("UPDATE product SET slug = :slug WHERE id = :id"),
            {"slug": slug_with_id, "id": product_id}
        )

    # Step 3: Make NOT NULL and Unique
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)
        batch_op.create_index(batch_op.f('ix_product_slug'), ['slug'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
