"""add contract fields to order

Revision ID: cbebaf841e20
Revises: fd50cb028045
Create Date: 2026-01-19 19:12:03.206377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbebaf841e20'
down_revision: Union[str, Sequence[str], None] = 'fd50cb028045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contract_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('contract_date')
        batch_op.drop_column('contract_number')

    # ### end Alembic commands ###
