"""remove contract_number from order

Revision ID: dec193022d0d
Revises: cbebaf841e20
Create Date: 2026-01-19 19:28:09.911458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec193022d0d'
down_revision: Union[str, Sequence[str], None] = 'cbebaf841e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('contract_number')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_number', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
