"""Add target currency fields to Order

Revision ID: e78bad921d0d
Revises: aa11bb22cc33
Create Date: 2026-03-11 05:50:06.473712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e78bad921d0d'
down_revision: Union[str, Sequence[str], None] = 'aa11bb22cc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('target_currency_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_currency_payments', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('target_currency_payments')
        batch_op.drop_column('target_currency_amount')
        batch_op.drop_column('target_currency')

    # ### end Alembic commands ###
