"""Add lead_source and comment to Order

Revision ID: f37e06766b7c
Revises: f3f1ac945939
Create Date: 2026-01-24 09:23:53.284913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f37e06766b7c'
down_revision: Union[str, Sequence[str], None] = 'f3f1ac945939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_lead_source'), ['lead_source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_lead_source'))
        batch_op.drop_column('comment')
        batch_op.drop_column('lead_source')

    # ### end Alembic commands ###
