"""Add OrderDocument model for Google Drive integration

Revision ID: fd50cb028045
Revises: 525d8f1ff545
Create Date: 2026-01-19 11:17:10.819513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd50cb028045'
down_revision: Union[str, Sequence[str], None] = '525d8f1ff545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('google_file_id', sa.String(), nullable=False),
    sa.Column('google_edit_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_document_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_document_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_document_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_document_doc_type'))

    op.drop_table('order_document')
    # ### end Alembic commands ###
