/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddressSuggestionItem } from './models/AddressSuggestionItem';
export type { AddressSuggestResponse } from './models/AddressSuggestResponse';
export type { ArticleResponse } from './models/ArticleResponse';
export type { Body_bulk_upload_local_images } from './models/Body_bulk_upload_local_images';
export type { Body_login_access_token } from './models/Body_login_access_token';
export type { Body_upload_images_admin_api_upload_images_post } from './models/Body_upload_images_admin_api_upload_images_post';
export type { Body_upload_local_images } from './models/Body_upload_local_images';
export type { Body_upload_manager_customer_contract } from './models/Body_upload_manager_customer_contract';
export type { Body_upload_manager_order_document } from './models/Body_upload_manager_order_document';
export type { BulkGalleryAddRequest } from './models/BulkGalleryAddRequest';
export type { BulkGalleryDeleteRequest } from './models/BulkGalleryDeleteRequest';
export type { BulkProductIdsRequest } from './models/BulkProductIdsRequest';
export type { BulkRoundRequest } from './models/BulkRoundRequest';
export type { BulkSpecUpdate } from './models/BulkSpecUpdate';
export type { CalendarEventResponse } from './models/CalendarEventResponse';
export type { CalendarEventType } from './models/CalendarEventType';
export type { CartItemPayload } from './models/CartItemPayload';
export type { CatalogImportPayload } from './models/CatalogImportPayload';
export type { CatalogImportResultResponse } from './models/CatalogImportResultResponse';
export type { CatalogResponse } from './models/CatalogResponse';
export type { CommonGalleryImageResponse } from './models/CommonGalleryImageResponse';
export type { CustomerPayload } from './models/CustomerPayload';
export type { DashboardContractExpiry } from './models/DashboardContractExpiry';
export type { DashboardStatsResponse } from './models/DashboardStatsResponse';
export type { DashboardTouchpoint } from './models/DashboardTouchpoint';
export type { DocumentTemplateItem } from './models/DocumentTemplateItem';
export type { DocumentTemplateListResponse } from './models/DocumentTemplateListResponse';
export type { FilterRange } from './models/FilterRange';
export type { FiltersConfigResponse } from './models/FiltersConfigResponse';
export type { FilterTagOption } from './models/FilterTagOption';
export type { FxRateResponse } from './models/FxRateResponse';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { LeadCreatePayload } from './models/LeadCreatePayload';
export type { LeadListResponse } from './models/LeadListResponse';
export type { LeadLossPayload } from './models/LeadLossPayload';
export type { LeadQualifyPayload } from './models/LeadQualifyPayload';
export type { LeadQualifyResponse } from './models/LeadQualifyResponse';
export type { LeadResponse } from './models/LeadResponse';
export type { LeadsCounterResponse } from './models/LeadsCounterResponse';
export type { LeadsInboxItemResponse } from './models/LeadsInboxItemResponse';
export type { LeadsInboxListResponse } from './models/LeadsInboxListResponse';
export type { LeadUpdatePayload } from './models/LeadUpdatePayload';
export type { ManagerActionMessageResponse } from './models/ManagerActionMessageResponse';
export type { ManagerAuthStatusResponse } from './models/ManagerAuthStatusResponse';
export type { ManagerBackupItemResponse } from './models/ManagerBackupItemResponse';
export type { ManagerBackupListResponse } from './models/ManagerBackupListResponse';
export type { ManagerBackupRunStartResponse } from './models/ManagerBackupRunStartResponse';
export type { ManagerBackupRunStatusResponse } from './models/ManagerBackupRunStatusResponse';
export type { ManagerBrandCreatePayload } from './models/ManagerBrandCreatePayload';
export type { ManagerBrandListResponse } from './models/ManagerBrandListResponse';
export type { ManagerBrandResponse } from './models/ManagerBrandResponse';
export type { ManagerBrandUpdatePayload } from './models/ManagerBrandUpdatePayload';
export type { ManagerBulkDeleteProductsError } from './models/ManagerBulkDeleteProductsError';
export type { ManagerBulkDeleteProductsResponse } from './models/ManagerBulkDeleteProductsResponse';
export type { ManagerBulkRoundPriceResponse } from './models/ManagerBulkRoundPriceResponse';
export type { ManagerBulkSetRrcPriceResponse } from './models/ManagerBulkSetRrcPriceResponse';
export type { ManagerBulkSpecsResponse } from './models/ManagerBulkSpecsResponse';
export type { ManagerCatalogCustomerItemResponse } from './models/ManagerCatalogCustomerItemResponse';
export type { ManagerCatalogCustomerListResponse } from './models/ManagerCatalogCustomerListResponse';
export type { ManagerCatalogProductImageResponse } from './models/ManagerCatalogProductImageResponse';
export type { ManagerCatalogProductItemResponse } from './models/ManagerCatalogProductItemResponse';
export type { ManagerCatalogProductListResponse } from './models/ManagerCatalogProductListResponse';
export type { ManagerCatalogProductManualResponse } from './models/ManagerCatalogProductManualResponse';
export type { ManagerCatalogProductTagResponse } from './models/ManagerCatalogProductTagResponse';
export type { ManagerCrmHealthReportResponse } from './models/ManagerCrmHealthReportResponse';
export type { ManagerCustomerBranchCreatePayload } from './models/ManagerCustomerBranchCreatePayload';
export type { ManagerCustomerBranchItemResponse } from './models/ManagerCustomerBranchItemResponse';
export type { ManagerCustomerBranchListResponse } from './models/ManagerCustomerBranchListResponse';
export type { ManagerCustomerBranchUpdatePayload } from './models/ManagerCustomerBranchUpdatePayload';
export type { ManagerCustomerContractCreatePayload } from './models/ManagerCustomerContractCreatePayload';
export type { ManagerCustomerContractItemResponse } from './models/ManagerCustomerContractItemResponse';
export type { ManagerCustomerContractListResponse } from './models/ManagerCustomerContractListResponse';
export type { ManagerCustomerContractUpdatePayload } from './models/ManagerCustomerContractUpdatePayload';
export type { ManagerCustomerDocumentItem } from './models/ManagerCustomerDocumentItem';
export type { ManagerCustomerDocumentListResponse } from './models/ManagerCustomerDocumentListResponse';
export type { ManagerCustomerUpdatePayload } from './models/ManagerCustomerUpdatePayload';
export type { ManagerEstimateLineResponse } from './models/ManagerEstimateLineResponse';
export type { ManagerEstimateRuleInputPayload } from './models/ManagerEstimateRuleInputPayload';
export type { ManagerGoogleAuthExchangePayload } from './models/ManagerGoogleAuthExchangePayload';
export type { ManagerGoogleAuthStatusResponse } from './models/ManagerGoogleAuthStatusResponse';
export type { ManagerGoogleAuthUrlResponse } from './models/ManagerGoogleAuthUrlResponse';
export type { ManagerInstallerCreatePayload } from './models/ManagerInstallerCreatePayload';
export type { ManagerInstallerListResponse } from './models/ManagerInstallerListResponse';
export type { ManagerInstallerResponse } from './models/ManagerInstallerResponse';
export type { ManagerInstallerUpdatePayload } from './models/ManagerInstallerUpdatePayload';
export type { ManagerInstallEstimateCalculatePayload } from './models/ManagerInstallEstimateCalculatePayload';
export type { ManagerInstallEstimateResponse } from './models/ManagerInstallEstimateResponse';
export type { ManagerInstallEstimateSavePayload } from './models/ManagerInstallEstimateSavePayload';
export type { ManagerMediaBulkAddResponse } from './models/ManagerMediaBulkAddResponse';
export type { ManagerMediaBulkDeleteResponse } from './models/ManagerMediaBulkDeleteResponse';
export type { ManagerMediaBulkUploadResponse } from './models/ManagerMediaBulkUploadResponse';
export type { ManagerMediaCleanupResponse } from './models/ManagerMediaCleanupResponse';
export type { ManagerMediaDeleteImageResponse } from './models/ManagerMediaDeleteImageResponse';
export type { ManagerMediaImageLinkResponse } from './models/ManagerMediaImageLinkResponse';
export type { ManagerMediaImageSearchResultResponse } from './models/ManagerMediaImageSearchResultResponse';
export type { ManagerMediaReuseImageResponse } from './models/ManagerMediaReuseImageResponse';
export type { ManagerMediaReuseSearchItemResponse } from './models/ManagerMediaReuseSearchItemResponse';
export type { ManagerMediaSetMainImageResponse } from './models/ManagerMediaSetMainImageResponse';
export type { ManagerMediaUploadLocalImagesResponse } from './models/ManagerMediaUploadLocalImagesResponse';
export type { ManagerNormalizeLegacySpecsResponse } from './models/ManagerNormalizeLegacySpecsResponse';
export type { ManagerOrderCreatePayload } from './models/ManagerOrderCreatePayload';
export type { ManagerOrderDetailResponse } from './models/ManagerOrderDetailResponse';
export type { ManagerOrderDocumentItem } from './models/ManagerOrderDocumentItem';
export type { ManagerOrderDocumentListResponse } from './models/ManagerOrderDocumentListResponse';
export type { ManagerOrderDocumentResponse } from './models/ManagerOrderDocumentResponse';
export type { ManagerOrderListItemResponse } from './models/ManagerOrderListItemResponse';
export type { ManagerOrderListResponse } from './models/ManagerOrderListResponse';
export type { ManagerOrderProductLinePayload } from './models/ManagerOrderProductLinePayload';
export type { ManagerOrderServiceLinePayload } from './models/ManagerOrderServiceLinePayload';
export type { ManagerOrderUpdatePayload } from './models/ManagerOrderUpdatePayload';
export type { ManagerQuickTariffListResponse } from './models/ManagerQuickTariffListResponse';
export type { ManagerQuickTariffResponse } from './models/ManagerQuickTariffResponse';
export type { ManagerRestoreJobStartResponse } from './models/ManagerRestoreJobStartResponse';
export type { ManagerRestoreJobStatusResponse } from './models/ManagerRestoreJobStatusResponse';
export type { ManagerServiceEstimateListResponse } from './models/ManagerServiceEstimateListResponse';
export type { ManagerServiceEstimateOrderLinesMode } from './models/ManagerServiceEstimateOrderLinesMode';
export type { ManagerServiceEstimateOrderLinesResponse } from './models/ManagerServiceEstimateOrderLinesResponse';
export type { ManagerServiceEstimateResponse } from './models/ManagerServiceEstimateResponse';
export type { ManagerSettingCreatePayload } from './models/ManagerSettingCreatePayload';
export type { ManagerSettingListResponse } from './models/ManagerSettingListResponse';
export type { ManagerSettingResponse } from './models/ManagerSettingResponse';
export type { ManagerSettingUpdatePayload } from './models/ManagerSettingUpdatePayload';
export type { ManagerTagCreatePayload } from './models/ManagerTagCreatePayload';
export type { ManagerTagGroupCreatePayload } from './models/ManagerTagGroupCreatePayload';
export type { ManagerTagGroupResponse } from './models/ManagerTagGroupResponse';
export type { ManagerTagGroupUpdatePayload } from './models/ManagerTagGroupUpdatePayload';
export type { ManagerTagOptionResponse } from './models/ManagerTagOptionResponse';
export type { ManagerTagUpdatePayload } from './models/ManagerTagUpdatePayload';
export type { ManagerTariffBriefResponse } from './models/ManagerTariffBriefResponse';
export type { ManagerTariffCreatePayload } from './models/ManagerTariffCreatePayload';
export type { ManagerTariffListResponse } from './models/ManagerTariffListResponse';
export type { ManagerTariffResponse } from './models/ManagerTariffResponse';
export type { ManagerTariffRuleCreatePayload } from './models/ManagerTariffRuleCreatePayload';
export type { ManagerTariffRuleListResponse } from './models/ManagerTariffRuleListResponse';
export type { ManagerTariffRuleResponse } from './models/ManagerTariffRuleResponse';
export type { ManagerTariffRuleType } from './models/ManagerTariffRuleType';
export type { ManagerTariffRuleUpdatePayload } from './models/ManagerTariffRuleUpdatePayload';
export type { ManagerTariffServiceKind } from './models/ManagerTariffServiceKind';
export type { ManagerTariffUpdatePayload } from './models/ManagerTariffUpdatePayload';
export type { Meta } from './models/Meta';
export type { OrderCustomerBranchBrief } from './models/OrderCustomerBranchBrief';
export type { OrderCustomerBrief } from './models/OrderCustomerBrief';
export type { OrderCustomerContractBrief } from './models/OrderCustomerContractBrief';
export type { OrderPayload } from './models/OrderPayload';
export type { OrderProductLineResponse } from './models/OrderProductLineResponse';
export type { OrderResponse } from './models/OrderResponse';
export type { OrderServiceLineResponse } from './models/OrderServiceLineResponse';
export type { OrderStatusUpdate } from './models/OrderStatusUpdate';
export type { OrderWorkStageCreatePayload } from './models/OrderWorkStageCreatePayload';
export type { OrderWorkStageResponse } from './models/OrderWorkStageResponse';
export type { OrderWorkStageUpdatePayload } from './models/OrderWorkStageUpdatePayload';
export type { PaymentCreatePayload } from './models/PaymentCreatePayload';
export type { PaymentCurrency } from './models/PaymentCurrency';
export type { PaymentResponse } from './models/PaymentResponse';
export type { ProductAvailabilityLeadPayload } from './models/ProductAvailabilityLeadPayload';
export type { ProductAvailabilityLeadResponse } from './models/ProductAvailabilityLeadResponse';
export type { ProductImageResponse } from './models/ProductImageResponse';
export type { ProductLocalStockPayload } from './models/ProductLocalStockPayload';
export type { ProductLocalStockResponse } from './models/ProductLocalStockResponse';
export type { ProductManualPayload } from './models/ProductManualPayload';
export type { ProductManualResponse } from './models/ProductManualResponse';
export type { ProductResponse } from './models/ProductResponse';
export type { ProductSiblingResponse } from './models/ProductSiblingResponse';
export type { ProductUpdate } from './models/ProductUpdate';
export type { ServiceResponse } from './models/ServiceResponse';
export type { SpecsKeysResponse } from './models/SpecsKeysResponse';
export type { SupplierCreatePayload } from './models/SupplierCreatePayload';
export type { SupplierListResponse } from './models/SupplierListResponse';
export type { SupplierMappingBulkCreatePayload } from './models/SupplierMappingBulkCreatePayload';
export type { SupplierMappingBulkCreateResponse } from './models/SupplierMappingBulkCreateResponse';
export type { SupplierMappingBulkErrorResponse } from './models/SupplierMappingBulkErrorResponse';
export type { SupplierMappingBulkItemPayload } from './models/SupplierMappingBulkItemPayload';
export type { SupplierMappingCreatePayload } from './models/SupplierMappingCreatePayload';
export type { SupplierMappingResponse } from './models/SupplierMappingResponse';
export type { SupplierOfferListResponse } from './models/SupplierOfferListResponse';
export type { SupplierOfferResponse } from './models/SupplierOfferResponse';
export type { SupplierOfferSuggestionCandidate } from './models/SupplierOfferSuggestionCandidate';
export type { SupplierOfferSuggestionItem } from './models/SupplierOfferSuggestionItem';
export type { SupplierOfferSuggestionRequestItem } from './models/SupplierOfferSuggestionRequestItem';
export type { SupplierOfferSuggestionsPayload } from './models/SupplierOfferSuggestionsPayload';
export type { SupplierOfferSuggestionsResponse } from './models/SupplierOfferSuggestionsResponse';
export type { SupplierPriceSourceCreatePayload } from './models/SupplierPriceSourceCreatePayload';
export type { SupplierPriceSourceListResponse } from './models/SupplierPriceSourceListResponse';
export type { SupplierPriceSourceResponse } from './models/SupplierPriceSourceResponse';
export type { SupplierPriceSourceUpdatePayload } from './models/SupplierPriceSourceUpdatePayload';
export type { SupplierResponse } from './models/SupplierResponse';
export type { SupplierSheetTabListResponse } from './models/SupplierSheetTabListResponse';
export type { SupplierSheetTabResponse } from './models/SupplierSheetTabResponse';
export type { SupplierSyncRunResponse } from './models/SupplierSyncRunResponse';
export type { SupplierUpdatePayload } from './models/SupplierUpdatePayload';
export type { TagGroupResponse } from './models/TagGroupResponse';
export type { TagResponse } from './models/TagResponse';
export type { ValidationError } from './models/ValidationError';

export { AdminService } from './services/AdminService';
export { AdminAnalyticsService } from './services/AdminAnalyticsService';
export { AdminDocsService } from './services/AdminDocsService';
export { AdminImportService } from './services/AdminImportService';
export { AdminMediaService } from './services/AdminMediaService';
export { AdminOrdersService } from './services/AdminOrdersService';
export { AdminScheduleService } from './services/AdminScheduleService';
export { ApiService } from './services/ApiService';
export { LoginService } from './services/LoginService';
export { ManagerService } from './services/ManagerService';
export { ManagerBackupsService } from './services/ManagerBackupsService';
export { ManagerBrandsService } from './services/ManagerBrandsService';
export { ManagerCalendarService } from './services/ManagerCalendarService';
export { ManagerContractsService } from './services/ManagerContractsService';
export { ManagerCrmService } from './services/ManagerCrmService';
export { ManagerDashboardService } from './services/ManagerDashboardService';
export { ManagerDocsService } from './services/ManagerDocsService';
export { ManagerGoogleAuthService } from './services/ManagerGoogleAuthService';
export { ManagerInstallersService } from './services/ManagerInstallersService';
export { ManagerLeadsService } from './services/ManagerLeadsService';
export { ManagerLeadsInboxService } from './services/ManagerLeadsInboxService';
export { ManagerOrdersService } from './services/ManagerOrdersService';
export { ManagerServiceEstimatesService } from './services/ManagerServiceEstimatesService';
export { ManagerSettingsService } from './services/ManagerSettingsService';
export { ManagerTagsService } from './services/ManagerTagsService';
export { ManagerTariffsService } from './services/ManagerTariffsService';
export { SystemService } from './services/SystemService';
