#!/usr/bin/env python3
"""Render exact Apache/Nginx legacy URL rules from scripts/seo/legacy_url_rules.py."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.seo.legacy_url_rules import GONE_RULES, LEGACY_REDIRECT_RULES

DEFAULT_HTACCESS = ROOT / "web" / "public" / ".htaccess"
DEFAULT_NGINX = ROOT / "deployment" / "nginx" / "mvn-seo-legacy-url-rules.conf"


def _split_source(source: str) -> tuple[str, str]:
    parsed = urlsplit(source)
    return parsed.path or "/", parsed.query


def _apache_path_pattern(path: str) -> str:
    clean = path.lstrip("/")
    escaped = re.escape(clean)
    return f"^{escaped}/?$"


def _apache_index_rule(path: str) -> str:
    return f"^{re.escape(path.lstrip('/'))}$"


def _render_apache() -> str:
    lines = [
        "# BEGIN MVN SEO legacy URL rules",
        "# Generated by: python3 scripts/seo/generate_legacy_server_rules.py",
        "# Exact-only rules for Yandex cleanup. Do not add broad product_id Clean-param rules here.",
        "<IfModule mod_rewrite.c>",
        "RewriteEngine On",
        "",
        "# Canonical legacy redirects.",
    ]

    for rule in LEGACY_REDIRECT_RULES:
        path, query = _split_source(rule.source)
        if query:
            lines.append(f"RewriteCond %{{QUERY_STRING}} ^{re.escape(query)}$ [NC]")
            lines.append(f"RewriteRule {_apache_index_rule(path)} {rule.target} [R=301,L,QSD]")
        else:
            lines.append(f"RewriteRule {_apache_path_pattern(path)} {rule.target} [R=301,L,QSD]")

    lines.extend(["", "# Obsolete product/manufacturer URLs: return 410 Gone."])
    for rule in GONE_RULES:
        path, query = _split_source(rule.source)
        if query:
            lines.append(f"RewriteCond %{{QUERY_STRING}} ^{re.escape(query)}$ [NC]")
            lines.append(f"RewriteRule {_apache_index_rule(path)} - [G,L]")
        else:
            lines.append(f"RewriteRule {_apache_path_pattern(path)} - [G,L]")

    lines.extend(["</IfModule>", "# END MVN SEO legacy URL rules", ""])
    return "\n".join(lines)


def _nginx_location_gone(path: str) -> list[str]:
    clean = path.rstrip("/") or "/"
    if clean == "/":
        return ["location = / { return 410; }"]
    return [f"location = {clean} {{ return 410; }}", f"location = {clean}/ {{ return 410; }}"]


def _render_nginx() -> str:
    lines = [
        "# MVN SEO legacy URL rules",
        "# Generated by: python3 scripts/seo/generate_legacy_server_rules.py",
        "# Include inside the mvn.by server block before generic static locations.",
        "# Exact-only rules for Yandex cleanup. Do not add broad product_id Clean-param rules here.",
        "",
        "# Canonical legacy redirects.",
    ]
    for rule in LEGACY_REDIRECT_RULES:
        lines.append(f'if ($request_uri = "{rule.source}") {{ return 301 {rule.target}; }}')

    lines.extend(["", "# Obsolete product/manufacturer URLs: return 410 Gone."])
    for rule in GONE_RULES:
        path, query = _split_source(rule.source)
        if query:
            lines.append(f'if ($request_uri = "{rule.source}") {{ return 410; }}')
        else:
            lines.extend(_nginx_location_gone(path))

    lines.append("")
    return "\n".join(lines)


def write_rules(htaccess: Path = DEFAULT_HTACCESS, nginx: Path = DEFAULT_NGINX) -> None:
    htaccess.parent.mkdir(parents=True, exist_ok=True)
    nginx.parent.mkdir(parents=True, exist_ok=True)
    htaccess.write_text(_render_apache(), encoding="utf-8")
    nginx.write_text(_render_nginx(), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--htaccess", type=Path, default=DEFAULT_HTACCESS)
    parser.add_argument("--nginx", type=Path, default=DEFAULT_NGINX)
    args = parser.parse_args()

    write_rules(args.htaccess, args.nginx)
    print(f"Wrote {args.htaccess}")
    print(f"Wrote {args.nginx}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
