"""Explicit event and template allowlists for tenant website notifications."""

INSTALLATION_ESTIMATE_LEAD_CREATED_EVENT = (
    "crm.installation_estimate_lead.created"
)
TENANT_WEBSITE_CHECKOUT_CREATED_EVENT = "tenant.website.checkout.created"
TENANT_WEBSITE_CONTACT_LEAD_CREATED_EVENT = (
    "tenant.website.contact_lead.created"
)
TENANT_WEBSITE_AVAILABILITY_REQUESTED_EVENT = (
    "tenant.website.product_availability.requested"
)
TENANT_WEBSITE_REPAIR_DIAGNOSTIC_CREATED_EVENT = (
    "tenant.website.repair_diagnostic.created"
)

INSTALLATION_ESTIMATE_TEMPLATE_KEY = (
    "telegram.installation_estimate_lead_created"
)
TENANT_WEBSITE_CHECKOUT_TEMPLATE_KEY = (
    "telegram.tenant_website_checkout_created"
)
TENANT_WEBSITE_CONTACT_TEMPLATE_KEY = (
    "telegram.tenant_website_contact_lead_created"
)
TENANT_WEBSITE_AVAILABILITY_TEMPLATE_KEY = (
    "telegram.tenant_website_product_availability_requested"
)
TENANT_WEBSITE_REPAIR_TEMPLATE_KEY = (
    "telegram.tenant_website_repair_diagnostic_created"
)

# This tuple is the reviewed production activation surface. Do not derive it
# from every registered renderer: dormant legacy events must stay dormant.
TENANT_WEBSITE_EVENT_TYPES = (
    INSTALLATION_ESTIMATE_LEAD_CREATED_EVENT,
    TENANT_WEBSITE_CHECKOUT_CREATED_EVENT,
    TENANT_WEBSITE_CONTACT_LEAD_CREATED_EVENT,
    TENANT_WEBSITE_AVAILABILITY_REQUESTED_EVENT,
    TENANT_WEBSITE_REPAIR_DIAGNOSTIC_CREATED_EVENT,
)
TENANT_WEBSITE_TEMPLATE_KEYS = (
    INSTALLATION_ESTIMATE_TEMPLATE_KEY,
    TENANT_WEBSITE_CHECKOUT_TEMPLATE_KEY,
    TENANT_WEBSITE_CONTACT_TEMPLATE_KEY,
    TENANT_WEBSITE_AVAILABILITY_TEMPLATE_KEY,
    TENANT_WEBSITE_REPAIR_TEMPLATE_KEY,
)

TENANT_WEBSITE_EVENT_TEMPLATE_KEYS = {
    INSTALLATION_ESTIMATE_LEAD_CREATED_EVENT: INSTALLATION_ESTIMATE_TEMPLATE_KEY,
    TENANT_WEBSITE_CHECKOUT_CREATED_EVENT: TENANT_WEBSITE_CHECKOUT_TEMPLATE_KEY,
    TENANT_WEBSITE_CONTACT_LEAD_CREATED_EVENT: TENANT_WEBSITE_CONTACT_TEMPLATE_KEY,
    TENANT_WEBSITE_AVAILABILITY_REQUESTED_EVENT: TENANT_WEBSITE_AVAILABILITY_TEMPLATE_KEY,
    TENANT_WEBSITE_REPAIR_DIAGNOSTIC_CREATED_EVENT: TENANT_WEBSITE_REPAIR_TEMPLATE_KEY,
}
