"""Stable operationId constants for manager API routes."""

READ_USER_ME = "read_user_me"
GET_MANAGER_CALENDAR_EVENTS = "get_manager_calendar_events"

GET_MANAGER_PRODUCTS = "get_manager_products"
GET_MANAGER_CUSTOMERS = "get_manager_customers"
GET_MANAGER_CUSTOMER_DETAIL = "get_manager_customer_detail"
GET_MANAGER_CUSTOMER_DOCS = "get_manager_customer_docs"
GET_MANAGER_CUSTOMER_BRANCHES = "get_manager_customer_branches"
CREATE_MANAGER_CUSTOMER_BRANCH = "create_manager_customer_branch"
PATCH_MANAGER_CUSTOMER_BRANCH = "patch_manager_customer_branch"
DELETE_MANAGER_CUSTOMER_BRANCH = "delete_manager_customer_branch"
GET_MANAGER_CUSTOMER_CONTRACTS = "get_manager_customer_contracts"
CREATE_MANAGER_CUSTOMER_CONTRACT = "create_manager_customer_contract"
UPLOAD_MANAGER_CUSTOMER_CONTRACT = "upload_manager_customer_contract"
PATCH_MANAGER_CUSTOMER_CONTRACT = "patch_manager_customer_contract"
ARCHIVE_MANAGER_CUSTOMER_CONTRACT = "archive_manager_customer_contract"
DELETE_MANAGER_CUSTOMER_CONTRACT = "delete_manager_customer_contract"
PATCH_MANAGER_CUSTOMER = "patch_manager_customer"
DELETE_MANAGER_CUSTOMER = "delete_manager_customer"
UPDATE_PRODUCT = "update_product"
DELETE_MANAGER_PRODUCT = "delete_manager_product"
BULK_ROUND_PRICE = "bulk_round_price"
BULK_SET_RRC_PRICE = "bulk_set_rrc_price"
BULK_DELETE_MANAGER_PRODUCTS = "bulk_delete_manager_products"
GET_ALL_TAGS = "get_all_tags"
SMART_SEARCH_PRODUCTS = "smart_search_products"

BULK_UPDATE_SPECS = "bulk_update_specs"
NORMALIZE_LEGACY_SPECS = "normalize_legacy_specs"

SEARCH_IMAGES = "search_images"
UPLOAD_IMAGE = "upload_image"
UPLOAD_LOCAL_IMAGES = "upload_local_images"

REUSE_SEARCH = "reuse_search"
GET_COMMON_GALLERY_IMAGES = "get_common_gallery_images"
LINK_SEARCH_RESULT = "link_search_result"
SET_MAIN_IMAGE = "set_main_image"
DELETE_IMAGE = "delete_image"
REUSE_IMAGE = "reuse_image"
BULK_ADD_GALLERY_IMAGES = "bulk_add_gallery_images"
BULK_UPLOAD_LOCAL_IMAGES = "bulk_upload_local_images"
BULK_DELETE_COMMON_GALLERY_IMAGES = "bulk_delete_common_gallery_images"
CLEANUP_MEDIA = "cleanup_media"

GET_MANAGER_LEADS = "get_manager_leads"
CREATE_MANAGER_LEAD = "create_manager_lead"
PATCH_MANAGER_LEAD = "patch_manager_lead"
QUALIFY_MANAGER_LEAD = "qualify_manager_lead"
MARK_MANAGER_LEAD_LOST = "mark_manager_lead_lost"

GET_MANAGER_LEADS_COUNTER = "get_manager_leads_counter"
GET_MANAGER_LEADS_INBOX = "get_manager_leads_inbox"

GET_MANAGER_ORDERS = "get_manager_orders"
CREATE_MANAGER_ORDER = "create_manager_order"
GET_MANAGER_ORDER_DETAIL = "get_manager_order_detail"
PATCH_MANAGER_ORDER = "patch_manager_order"
DELETE_MANAGER_ORDER = "delete_manager_order"
GENERATE_MANAGER_ORDER_DOCUMENT = "generate_manager_order_document"
UPLOAD_MANAGER_ORDER_DOCUMENT = "upload_manager_order_document"
GET_MANAGER_ORDER_DOCUMENTS = "get_manager_order_documents"
ADD_MANAGER_ORDER_PAYMENT = "add_manager_order_payment"
DELETE_MANAGER_ORDER_PAYMENT = "delete_manager_order_payment"
CREATE_MANAGER_ORDER_STAGE = "create_manager_order_stage"
UPDATE_MANAGER_ORDER_STAGE = "update_manager_order_stage"
DELETE_MANAGER_ORDER_STAGE = "delete_manager_order_stage"
GET_MANAGER_DOC_DOWNLOAD = "get_manager_doc_download"
DELETE_MANAGER_DOC = "delete_manager_doc"
GET_DOC_TEMPLATES = "get_doc_templates"
GET_MANAGER_CRM_HEALTH_REPORT = "get_manager_crm_health_report"
GET_DASHBOARD_STATS = "get_dashboard_stats"
IMPORT_ONLINER = "import_onliner"
CATALOG_IMPORT = "catalog_import"

GET_MANAGER_INSTALLERS = "get_manager_installers"
CREATE_MANAGER_INSTALLER = "create_manager_installer"
UPDATE_MANAGER_INSTALLER = "update_manager_installer"
SEARCH_MANAGER_INSTALLERS = "search_manager_installers"

LIST_MANAGER_SETTINGS = "list_manager_settings"
GET_FX_RATE = "get_fx_rate"
SUGGEST_ADDRESS = "suggest_address"
UPDATE_MANAGER_SETTING = "update_manager_setting"
CREATE_MANAGER_SETTING = "create_manager_setting"
GET_MANAGER_GOOGLE_AUTH_STATUS = "get_manager_google_auth_status"
GET_MANAGER_GOOGLE_AUTH_URL = "get_manager_google_auth_url"
EXCHANGE_MANAGER_GOOGLE_AUTH_CODE = "exchange_manager_google_auth_code"
LIST_MANAGER_BACKUPS = "list_manager_backups"
START_MANAGER_BACKUP_RUN = "start_manager_backup_run"
GET_MANAGER_BACKUP_RUN_STATUS = "get_manager_backup_run_status"
START_MANAGER_BACKUP_RESTORE = "start_manager_backup_restore"
GET_MANAGER_BACKUP_RESTORE_STATUS = "get_manager_backup_restore_status"

LIST_MANAGER_TARIFFS = "list_manager_tariffs"
LIST_MANAGER_QUICK_TARIFFS = "list_manager_quick_tariffs"
CREATE_MANAGER_TARIFF = "create_manager_tariff"
UPDATE_MANAGER_TARIFF = "update_manager_tariff"
DELETE_MANAGER_TARIFF = "delete_manager_tariff"
LIST_MANAGER_TARIFF_RULES = "list_manager_tariff_rules"
CREATE_MANAGER_TARIFF_RULE = "create_manager_tariff_rule"
UPDATE_MANAGER_TARIFF_RULE = "update_manager_tariff_rule"
DELETE_MANAGER_TARIFF_RULE = "delete_manager_tariff_rule"
CALCULATE_MANAGER_INSTALL_ESTIMATE = "calculate_manager_install_estimate"
CREATE_MANAGER_SERVICE_ESTIMATE = "create_manager_service_estimate"
LIST_MANAGER_SERVICE_ESTIMATES = "list_manager_service_estimates"
GET_MANAGER_SERVICE_ESTIMATE = "get_manager_service_estimate"
DELETE_MANAGER_SERVICE_ESTIMATE = "delete_manager_service_estimate"
GET_MANAGER_SERVICE_ESTIMATE_ORDER_LINES = "get_manager_service_estimate_order_lines"

GET_MANAGER_TAG_GROUPS = "get_manager_tag_groups"
CREATE_MANAGER_TAG_GROUP = "create_manager_tag_group"
UPDATE_MANAGER_TAG_GROUP = "update_manager_tag_group"
DELETE_MANAGER_TAG_GROUP = "delete_manager_tag_group"
CREATE_MANAGER_TAG = "create_manager_tag"
UPDATE_MANAGER_TAG = "update_manager_tag"
DELETE_MANAGER_TAG = "delete_manager_tag"
LIST_MANAGER_BRANDS = "list_manager_brands"
CREATE_MANAGER_BRAND = "create_manager_brand"
UPDATE_MANAGER_BRAND = "update_manager_brand"
DELETE_MANAGER_BRAND = "delete_manager_brand"
LIST_SUPPLIERS = "list_suppliers"
CREATE_SUPPLIER = "create_supplier"
PATCH_SUPPLIER = "patch_supplier"
DELETE_SUPPLIER = "delete_supplier"
LIST_SUPPLIER_SOURCES = "list_supplier_sources"
CREATE_SUPPLIER_SOURCE = "create_supplier_source"
PATCH_SUPPLIER_SOURCE = "patch_supplier_source"
DELETE_SUPPLIER_SOURCE = "delete_supplier_source"
SYNC_SUPPLIER_SOURCE = "sync_supplier_source"
LIST_UNMAPPED_SUPPLIER_OFFERS = "list_unmapped_supplier_offers"
CREATE_SUPPLIER_MAPPING = "create_supplier_mapping"
DELETE_SUPPLIER_MAPPING = "delete_supplier_mapping"
GET_PRODUCT_SUPPLIER_OFFERS = "get_product_supplier_offers"
UPSERT_PRODUCT_LOCAL_STOCK = "upsert_product_local_stock"
LIST_SUPPLIER_SHEETS = "list_supplier_sheets"
SYNC_ALL_SUPPLIER_SOURCES = "sync_all_supplier_sources"
SUGGEST_SUPPLIER_OFFERS = "suggest_supplier_offers"
BULK_CREATE_SUPPLIER_MAPPINGS = "bulk_create_supplier_mappings"

ALL_MANAGER_OPERATION_IDS = (
    READ_USER_ME,
    GET_MANAGER_CALENDAR_EVENTS,
    GET_MANAGER_PRODUCTS,
    GET_MANAGER_CUSTOMERS,
    GET_MANAGER_CUSTOMER_DETAIL,
    GET_MANAGER_CUSTOMER_DOCS,
    GET_MANAGER_CUSTOMER_BRANCHES,
    CREATE_MANAGER_CUSTOMER_BRANCH,
    PATCH_MANAGER_CUSTOMER_BRANCH,
    DELETE_MANAGER_CUSTOMER_BRANCH,
    GET_MANAGER_CUSTOMER_CONTRACTS,
    CREATE_MANAGER_CUSTOMER_CONTRACT,
    UPLOAD_MANAGER_CUSTOMER_CONTRACT,
    PATCH_MANAGER_CUSTOMER_CONTRACT,
    ARCHIVE_MANAGER_CUSTOMER_CONTRACT,
    DELETE_MANAGER_CUSTOMER_CONTRACT,
    PATCH_MANAGER_CUSTOMER,
    DELETE_MANAGER_CUSTOMER,
    UPDATE_PRODUCT,
    DELETE_MANAGER_PRODUCT,
    BULK_ROUND_PRICE,
    BULK_SET_RRC_PRICE,
    BULK_DELETE_MANAGER_PRODUCTS,
    GET_ALL_TAGS,
    SMART_SEARCH_PRODUCTS,
    BULK_UPDATE_SPECS,
    NORMALIZE_LEGACY_SPECS,
    SEARCH_IMAGES,
    UPLOAD_IMAGE,
    UPLOAD_LOCAL_IMAGES,
    REUSE_SEARCH,
    GET_COMMON_GALLERY_IMAGES,
    LINK_SEARCH_RESULT,
    SET_MAIN_IMAGE,
    DELETE_IMAGE,
    REUSE_IMAGE,
    BULK_ADD_GALLERY_IMAGES,
    BULK_UPLOAD_LOCAL_IMAGES,
    BULK_DELETE_COMMON_GALLERY_IMAGES,
    CLEANUP_MEDIA,
    GET_MANAGER_LEADS,
    CREATE_MANAGER_LEAD,
    PATCH_MANAGER_LEAD,
    QUALIFY_MANAGER_LEAD,
    MARK_MANAGER_LEAD_LOST,
    GET_MANAGER_LEADS_COUNTER,
    GET_MANAGER_LEADS_INBOX,
    GET_MANAGER_ORDERS,
    CREATE_MANAGER_ORDER,
    GET_MANAGER_ORDER_DETAIL,
    PATCH_MANAGER_ORDER,
    DELETE_MANAGER_ORDER,
    GENERATE_MANAGER_ORDER_DOCUMENT,
    UPLOAD_MANAGER_ORDER_DOCUMENT,
    GET_MANAGER_ORDER_DOCUMENTS,
    ADD_MANAGER_ORDER_PAYMENT,
    DELETE_MANAGER_ORDER_PAYMENT,
    CREATE_MANAGER_ORDER_STAGE,
    UPDATE_MANAGER_ORDER_STAGE,
    DELETE_MANAGER_ORDER_STAGE,
    GET_MANAGER_DOC_DOWNLOAD,
    DELETE_MANAGER_DOC,
    GET_MANAGER_CRM_HEALTH_REPORT,
    GET_DASHBOARD_STATS,
    IMPORT_ONLINER,
    GET_MANAGER_INSTALLERS,
    CREATE_MANAGER_INSTALLER,
    UPDATE_MANAGER_INSTALLER,
    SEARCH_MANAGER_INSTALLERS,
    LIST_MANAGER_SETTINGS,
    CREATE_MANAGER_SETTING,
    GET_FX_RATE,
    SUGGEST_ADDRESS,
    UPDATE_MANAGER_SETTING,
    GET_MANAGER_GOOGLE_AUTH_STATUS,
    GET_MANAGER_GOOGLE_AUTH_URL,
    EXCHANGE_MANAGER_GOOGLE_AUTH_CODE,
    LIST_MANAGER_BACKUPS,
    START_MANAGER_BACKUP_RUN,
    GET_MANAGER_BACKUP_RUN_STATUS,
    START_MANAGER_BACKUP_RESTORE,
    GET_MANAGER_BACKUP_RESTORE_STATUS,
    LIST_MANAGER_TARIFFS,
    LIST_MANAGER_QUICK_TARIFFS,
    CREATE_MANAGER_TARIFF,
    UPDATE_MANAGER_TARIFF,
    DELETE_MANAGER_TARIFF,
    LIST_MANAGER_TARIFF_RULES,
    CREATE_MANAGER_TARIFF_RULE,
    UPDATE_MANAGER_TARIFF_RULE,
    DELETE_MANAGER_TARIFF_RULE,
    CALCULATE_MANAGER_INSTALL_ESTIMATE,
    CREATE_MANAGER_SERVICE_ESTIMATE,
    LIST_MANAGER_SERVICE_ESTIMATES,
    GET_MANAGER_SERVICE_ESTIMATE,
    DELETE_MANAGER_SERVICE_ESTIMATE,
    GET_MANAGER_SERVICE_ESTIMATE_ORDER_LINES,
    GET_MANAGER_TAG_GROUPS,
    CREATE_MANAGER_TAG_GROUP,
    UPDATE_MANAGER_TAG_GROUP,
    DELETE_MANAGER_TAG_GROUP,
    CREATE_MANAGER_TAG,
    UPDATE_MANAGER_TAG,
    DELETE_MANAGER_TAG,
    LIST_MANAGER_BRANDS,
    CREATE_MANAGER_BRAND,
    UPDATE_MANAGER_BRAND,
    DELETE_MANAGER_BRAND,
    LIST_SUPPLIERS,
    CREATE_SUPPLIER,
    PATCH_SUPPLIER,
    DELETE_SUPPLIER,
    LIST_SUPPLIER_SOURCES,
    CREATE_SUPPLIER_SOURCE,
    PATCH_SUPPLIER_SOURCE,
    DELETE_SUPPLIER_SOURCE,
    SYNC_SUPPLIER_SOURCE,
    LIST_UNMAPPED_SUPPLIER_OFFERS,
    CREATE_SUPPLIER_MAPPING,
    DELETE_SUPPLIER_MAPPING,
    GET_PRODUCT_SUPPLIER_OFFERS,
    UPSERT_PRODUCT_LOCAL_STOCK,
    LIST_SUPPLIER_SHEETS,
    SYNC_ALL_SUPPLIER_SOURCES,
    SUGGEST_SUPPLIER_OFFERS,
    BULK_CREATE_SUPPLIER_MAPPINGS,
    GET_DOC_TEMPLATES,
    CATALOG_IMPORT,
)
