"""Stable operationId constants for manager API routes."""

READ_USER_ME = "read_user_me"
GET_MANAGER_CALENDAR_EVENTS = "get_manager_calendar_events"

GET_MANAGER_PRODUCTS = "get_manager_products"
GET_MANAGER_PRODUCT = "get_manager_product"
GET_MANAGER_CATALOG_QUALITY_REPORT = "get_manager_catalog_quality_report"
GET_MANAGER_CUSTOMERS = "get_manager_customers"
GET_MANAGER_CUSTOMER_DETAIL = "get_manager_customer_detail"
GET_MANAGER_CUSTOMER_DOCS = "get_manager_customer_docs"
GET_MANAGER_CUSTOMER_RECONCILIATION = "get_manager_customer_reconciliation"
CREATE_MANAGER_CUSTOMER_RECONCILIATION_DOCUMENT = "create_manager_customer_reconciliation_document"
RECOGNIZE_MANAGER_CUSTOMER_REQUISITES = "recognize_manager_customer_requisites"
CONFIRM_MANAGER_CUSTOMER_REQUISITES = "confirm_manager_customer_requisites"
GET_MANAGER_CUSTOMER_BRANCHES = "get_manager_customer_branches"
CREATE_MANAGER_CUSTOMER_BRANCH = "create_manager_customer_branch"
PATCH_MANAGER_CUSTOMER_BRANCH = "patch_manager_customer_branch"
DELETE_MANAGER_CUSTOMER_BRANCH = "delete_manager_customer_branch"
LIST_MANAGER_EQUIPMENT = "list_manager_equipment"
CREATE_MANAGER_EQUIPMENT = "create_manager_equipment"
CREATE_MANAGER_EQUIPMENT_FROM_ORDER = "create_manager_equipment_from_order"
CREATE_MANAGER_MAINTENANCE_ORDER = "create_manager_maintenance_order"
GET_MANAGER_EQUIPMENT = "get_manager_equipment"
PATCH_MANAGER_EQUIPMENT = "patch_manager_equipment"
CREATE_MANAGER_EQUIPMENT_COMPONENT = "create_manager_equipment_component"
PATCH_MANAGER_EQUIPMENT_COMPONENT = "patch_manager_equipment_component"
LIST_MANAGER_EQUIPMENT_HISTORY = "list_manager_equipment_history"
CREATE_MANAGER_EQUIPMENT_HISTORY = "create_manager_equipment_history"
CREATE_MANAGER_EQUIPMENT_HISTORY_FROM_REPAIR_ORDER = "create_manager_equipment_history_from_repair_order"
LIST_MANAGER_ORDER_ATTACHMENTS = "list_manager_order_attachments"
LIST_MANAGER_EQUIPMENT_ATTACHMENTS = "list_manager_equipment_attachments"
UPLOAD_MANAGER_ORDER_ATTACHMENT = "upload_manager_order_attachment"
PATCH_MANAGER_SERVICE_ATTACHMENT = "patch_manager_service_attachment"
DELETE_MANAGER_SERVICE_ATTACHMENT = "delete_manager_service_attachment"
GET_MANAGER_SERVICE_ATTACHMENT_ACCESS = "get_manager_service_attachment_access"
LIST_MANAGER_ORDER_EQUIPMENT_LINKS = "list_manager_order_equipment_links"
CREATE_MANAGER_ORDER_EQUIPMENT_LINK = "create_manager_order_equipment_link"
DELETE_MANAGER_ORDER_EQUIPMENT_LINK = "delete_manager_order_equipment_link"
LIST_MANAGER_WARRANTY_POLICIES = "list_manager_warranty_policies"
CREATE_MANAGER_WARRANTY_POLICY = "create_manager_warranty_policy"
PATCH_MANAGER_WARRANTY_POLICY = "patch_manager_warranty_policy"
LIST_MANAGER_EQUIPMENT_WARRANTY_COVERAGES = "list_manager_equipment_warranty_coverages"
DECIDE_MANAGER_WARRANTY_COVERAGE = "decide_manager_warranty_coverage"
GET_MANAGER_CUSTOMER_CONTRACTS = "get_manager_customer_contracts"
CREATE_MANAGER_CUSTOMER_CONTRACT = "create_manager_customer_contract"
UPLOAD_MANAGER_CUSTOMER_CONTRACT = "upload_manager_customer_contract"
PATCH_MANAGER_CUSTOMER_CONTRACT = "patch_manager_customer_contract"
ARCHIVE_MANAGER_CUSTOMER_CONTRACT = "archive_manager_customer_contract"
DELETE_MANAGER_CUSTOMER_CONTRACT = "delete_manager_customer_contract"
PATCH_MANAGER_CUSTOMER = "patch_manager_customer"
DELETE_MANAGER_CUSTOMER = "delete_manager_customer"
CREATE_MANAGER_PRODUCT = "create_manager_product"
DUPLICATE_MANAGER_PRODUCT = "duplicate_manager_product"
UPDATE_PRODUCT = "update_product"
DELETE_MANAGER_PRODUCT = "delete_manager_product"
BULK_ROUND_PRICE = "bulk_round_price"
BULK_SET_RRC_PRICE = "bulk_set_rrc_price"
BULK_DELETE_MANAGER_PRODUCTS = "bulk_delete_manager_products"
GET_ALL_TAGS = "get_all_tags"
SMART_SEARCH_PRODUCTS = "smart_search_products"
GET_MANAGER_YANDEX_BUSINESS_PRICE_LIST = "get_manager_yandex_business_price_list"
GET_MANAGER_YANDEX_BUSINESS_QUALITY_REPORT = (
    "get_manager_yandex_business_quality_report"
)

BULK_UPDATE_SPECS = "bulk_update_specs"
NORMALIZE_LEGACY_SPECS = "normalize_legacy_specs"

SEARCH_IMAGES = "search_images"
UPLOAD_IMAGE = "upload_image"
UPLOAD_LOCAL_IMAGES = "upload_local_images"

REUSE_SEARCH = "reuse_search"
GET_COMMON_GALLERY_IMAGES = "get_common_gallery_images"
LINK_SEARCH_RESULT = "link_search_result"
SET_MAIN_IMAGE = "set_main_image"
DELETE_IMAGE = "delete_image"
CROP_PRODUCT_IMAGE = "crop_product_image"
REMOVE_PRODUCT_IMAGE_BACKGROUND = "remove_product_image_background"
REUSE_IMAGE = "reuse_image"
BULK_ADD_GALLERY_IMAGES = "bulk_add_gallery_images"
BULK_UPLOAD_LOCAL_IMAGES = "bulk_upload_local_images"
BULK_DELETE_COMMON_GALLERY_IMAGES = "bulk_delete_common_gallery_images"
APPLY_GALLERY_TO_SERIES = "apply_gallery_to_series"
CLEANUP_MEDIA = "cleanup_media"
GET_IMAGE_VARIANT_CANDIDATES = "get_image_variant_candidates"
PROCESS_MISSING_IMAGE_VARIANTS = "process_missing_image_variants"
REPROCESS_IMAGE_VARIANT = "reprocess_image_variant"
LIST_MEDIA_ASSETS = "list_media_assets"
GET_MEDIA_BACKGROUND_REMOVAL_CONFIG = "get_media_background_removal_config"
UPLOAD_MEDIA_ASSETS = "upload_media_assets"
UPLOAD_MEDIA_ASSET_FROM_URL = "upload_media_asset_from_url"
BACKFILL_REFERENCED_MEDIA_ASSETS = "backfill_referenced_media_assets"
UPDATE_MEDIA_ASSET = "update_media_asset"
DELETE_MEDIA_ASSET = "delete_media_asset"
CROP_MEDIA_ASSET = "crop_media_asset"
REMOVE_MEDIA_ASSET_BACKGROUND = "remove_media_asset_background"
CREATE_MEDIA_PROCESSING_JOB = "create_media_processing_job"
LIST_MEDIA_PROCESSING_JOBS = "list_media_processing_jobs"
CLAIM_MEDIA_WORKER_JOB = "claim_media_worker_job"
RENEW_MEDIA_WORKER_JOB = "renew_media_worker_job"
COMPLETE_MEDIA_WORKER_JOB = "complete_media_worker_job"
FAIL_MEDIA_WORKER_JOB = "fail_media_worker_job"
CREATE_MAIN_IMAGE_CLEANUP_BATCH = "create_main_image_cleanup_batch"
LIST_MAIN_IMAGE_CLEANUP_BATCHES = "list_main_image_cleanup_batches"
LIST_MAIN_IMAGE_CLEANUP_ITEMS = "list_main_image_cleanup_items"
APPROVE_MAIN_IMAGE_CLEANUP_ITEMS = "approve_main_image_cleanup_items"
REJECT_MAIN_IMAGE_CLEANUP_ITEMS = "reject_main_image_cleanup_items"
SKIP_MAIN_IMAGE_CLEANUP_ITEMS = "skip_main_image_cleanup_items"
LIST_MAIN_IMAGE_CLEANUP_SKIP_REASONS = "list_main_image_cleanup_skip_reasons"

GET_MANAGER_LEADS = "get_manager_leads"
CREATE_MANAGER_LEAD = "create_manager_lead"
PATCH_MANAGER_LEAD = "patch_manager_lead"
QUALIFY_MANAGER_LEAD = "qualify_manager_lead"
MARK_MANAGER_LEAD_LOST = "mark_manager_lead_lost"

GET_MANAGER_LEADS_COUNTER = "get_manager_leads_counter"
GET_MANAGER_LEADS_INBOX = "get_manager_leads_inbox"

GET_MANAGER_ORDERS = "get_manager_orders"
CREATE_MANAGER_ORDER = "create_manager_order"
EXPORT_MANAGER_ORDERS = "export_manager_orders"
PREVIEW_IMPORT_MANAGER_ORDERS = "preview_import_manager_orders"
IMPORT_MANAGER_ORDERS = "import_manager_orders"
GET_MANAGER_ORDER_DETAIL = "get_manager_order_detail"
PATCH_MANAGER_ORDER = "patch_manager_order"
DELETE_MANAGER_ORDER = "delete_manager_order"
CREATE_MANAGER_ORDER_PROPOSAL = "create_manager_order_proposal"
DUPLICATE_MANAGER_ORDER_PROPOSAL = "duplicate_manager_order_proposal"
PATCH_MANAGER_ORDER_PROPOSAL = "patch_manager_order_proposal"
ARCHIVE_MANAGER_ORDER_PROPOSAL = "archive_manager_order_proposal"
SELECT_MANAGER_ORDER_PROPOSAL = "select_manager_order_proposal"
GENERATE_MANAGER_ORDER_DOCUMENT = "generate_manager_order_document"
UPLOAD_MANAGER_ORDER_DOCUMENT = "upload_manager_order_document"
REGISTER_MANAGER_EXTERNAL_CONTRACT = "register_manager_external_contract"
GET_MANAGER_ORDER_DOCUMENTS = "get_manager_order_documents"
ATTACH_MANAGER_DOC_FILE = "attach_manager_doc_file"
ADD_MANAGER_ORDER_PAYMENT = "add_manager_order_payment"
DELETE_MANAGER_ORDER_PAYMENT = "delete_manager_order_payment"
CREATE_MANAGER_ORDER_STAGE = "create_manager_order_stage"
UPDATE_MANAGER_ORDER_STAGE = "update_manager_order_stage"
DELETE_MANAGER_ORDER_STAGE = "delete_manager_order_stage"
LIST_MANAGER_STALE_ORDER_STAGES = "list_manager_stale_order_stages"
CANCEL_MANAGER_ORDER_STAGE_DIRECT = "cancel_manager_order_stage_direct"
DELETE_MANAGER_ORDER_STAGE_DIRECT = "delete_manager_order_stage_direct"
GET_MANAGER_DOC_DOWNLOAD = "get_manager_doc_download"
DELETE_MANAGER_DOC = "delete_manager_doc"
IMPORT_MANAGER_BANK_RECEIPTS = "import_manager_bank_receipts"
IMPORT_MANAGER_BANK_STATEMENT = "import_manager_bank_statement"
IMPORT_MANAGER_EMAIL_LEADS = "import_manager_email_leads"
GET_MANAGER_EMAIL_LEAD_IMPORT_STATUS = "get_manager_email_lead_import_status"
LIST_MANAGER_BANK_RECEIPTS = "list_manager_bank_receipts"
ATTACH_MANAGER_BANK_RECEIPT = "attach_manager_bank_receipt"
ATTACH_MANAGER_BANK_RECEIPT_GROUP = "attach_manager_bank_receipt_group"
GET_MANAGER_BANK_RECEIPT_ALLOCATION = "get_manager_bank_receipt_allocation"
REPLACE_MANAGER_BANK_RECEIPT_ALLOCATIONS = "replace_manager_bank_receipt_allocations"
PATCH_MANAGER_BANK_RECEIPT_STATUS = "patch_manager_bank_receipt_status"
DELETE_MANAGER_BANK_RECEIPT = "delete_manager_bank_receipt"
LIST_MANAGER_OUTGOING_EMAILS = "list_manager_outgoing_emails"
GET_MANAGER_OUTGOING_EMAIL = "get_manager_outgoing_email"
LIST_MANAGER_ORDER_OUTGOING_EMAILS = "list_manager_order_outgoing_emails"
RETRY_MANAGER_OUTGOING_EMAIL = "retry_manager_outgoing_email"
SEND_MANAGER_TEST_EMAIL = "send_manager_test_email"
COMPOSE_MANAGER_ORDER_EMAIL = "compose_manager_order_email"
SEND_MANAGER_ORDER_EMAIL = "send_manager_order_email"
GET_DOC_TEMPLATES = "get_doc_templates"
LIST_MANAGER_DOCUMENT_TEMPLATES = "list_manager_document_templates"
LIST_MANAGER_DOCUMENT_TEMPLATE_FILES = "list_manager_document_template_files"
CREATE_MANAGER_DOCUMENT_TEMPLATE = "create_manager_document_template"
PATCH_MANAGER_DOCUMENT_TEMPLATE = "patch_manager_document_template"
DELETE_MANAGER_DOCUMENT_TEMPLATE = "delete_manager_document_template"
GET_MANAGER_CRM_HEALTH_REPORT = "get_manager_crm_health_report"
GET_DASHBOARD_STATS = "get_dashboard_stats"
IMPORT_ONLINER = "import_onliner"
CATALOG_IMPORT = "catalog_import"
START_CATALOG_IMPORT_JOB = "start_catalog_import_job"
GET_CATALOG_IMPORT_JOB_STATUS = "get_catalog_import_job_status"
GET_CURRENT_CATALOG_IMPORT_JOB_STATUS = "get_current_catalog_import_job_status"
PREVIEW_MDV_CATALOG_IMPORT = "preview_mdv_catalog_import"
START_MDV_CATALOG_IMPORT_JOB = "start_mdv_catalog_import_job"

GET_MANAGER_INSTALLERS = "get_manager_installers"
CREATE_MANAGER_INSTALLER = "create_manager_installer"
UPDATE_MANAGER_INSTALLER = "update_manager_installer"
SEARCH_MANAGER_INSTALLERS = "search_manager_installers"
LIST_MANAGER_STAFF = "list_manager_staff"
CREATE_MANAGER_STAFF = "create_manager_staff"
PATCH_MANAGER_STAFF = "patch_manager_staff"

LIST_MANAGER_SETTINGS = "list_manager_settings"
GET_FX_RATE = "get_fx_rate"
SUGGEST_ADDRESS = "suggest_address"
UPDATE_MANAGER_SETTING = "update_manager_setting"
CREATE_MANAGER_SETTING = "create_manager_setting"
GET_MANAGER_GOOGLE_AUTH_STATUS = "get_manager_google_auth_status"
GET_MANAGER_GOOGLE_AUTH_URL = "get_manager_google_auth_url"
LIST_MANAGER_BACKUPS = "list_manager_backups"
START_MANAGER_BACKUP_RUN = "start_manager_backup_run"
GET_MANAGER_BACKUP_RUN_STATUS = "get_manager_backup_run_status"
START_MANAGER_BACKUP_RESTORE = "start_manager_backup_restore"
GET_MANAGER_BACKUP_RESTORE_STATUS = "get_manager_backup_restore_status"

LIST_MANAGER_TARIFFS = "list_manager_tariffs"
LIST_MANAGER_QUICK_TARIFFS = "list_manager_quick_tariffs"
CREATE_MANAGER_TARIFF = "create_manager_tariff"
UPDATE_MANAGER_TARIFF = "update_manager_tariff"
DELETE_MANAGER_TARIFF = "delete_manager_tariff"
LIST_MANAGER_TARIFF_RULES = "list_manager_tariff_rules"
LIST_MANAGER_FAVORITE_TARIFF_RULES = "list_manager_favorite_tariff_rules"
CREATE_MANAGER_TARIFF_RULE = "create_manager_tariff_rule"
UPDATE_MANAGER_TARIFF_RULE = "update_manager_tariff_rule"
DELETE_MANAGER_TARIFF_RULE = "delete_manager_tariff_rule"
LIST_MANAGER_REPAIR_COMPLAINT_PRESETS = "list_manager_repair_complaint_presets"
CREATE_MANAGER_REPAIR_COMPLAINT_PRESET = "create_manager_repair_complaint_preset"
UPDATE_MANAGER_REPAIR_COMPLAINT_PRESET = "update_manager_repair_complaint_preset"
DELETE_MANAGER_REPAIR_COMPLAINT_PRESET = "delete_manager_repair_complaint_preset"
GENERATE_MANAGER_REPAIR_ACT_AI_DRAFT = "generate_manager_repair_act_ai_draft"
CALCULATE_MANAGER_INSTALL_ESTIMATE = "calculate_manager_install_estimate"
CREATE_MANAGER_SERVICE_ESTIMATE = "create_manager_service_estimate"
LIST_MANAGER_SERVICE_ESTIMATES = "list_manager_service_estimates"
GET_MANAGER_SERVICE_ESTIMATE = "get_manager_service_estimate"
DELETE_MANAGER_SERVICE_ESTIMATE = "delete_manager_service_estimate"
GET_MANAGER_SERVICE_ESTIMATE_ORDER_LINES = "get_manager_service_estimate_order_lines"

GET_MANAGER_TAG_GROUPS = "get_manager_tag_groups"
CREATE_MANAGER_TAG_GROUP = "create_manager_tag_group"
UPDATE_MANAGER_TAG_GROUP = "update_manager_tag_group"
DELETE_MANAGER_TAG_GROUP = "delete_manager_tag_group"
CREATE_MANAGER_TAG = "create_manager_tag"
UPDATE_MANAGER_TAG = "update_manager_tag"
DELETE_MANAGER_TAG = "delete_manager_tag"
LIST_MANAGER_BRANDS = "list_manager_brands"
CREATE_MANAGER_BRAND = "create_manager_brand"
UPDATE_MANAGER_BRAND = "update_manager_brand"
DELETE_MANAGER_BRAND = "delete_manager_brand"
LIST_MANAGER_BRAND_FEATURES = "list_manager_brand_features"
CREATE_MANAGER_BRAND_FEATURE = "create_manager_brand_feature"
UPDATE_MANAGER_BRAND_FEATURE = "update_manager_brand_feature"
DELETE_MANAGER_BRAND_FEATURE = "delete_manager_brand_feature"
LIST_MANAGER_BRAND_SERIES = "list_manager_brand_series"
CREATE_MANAGER_BRAND_SERIES = "create_manager_brand_series"
UPDATE_MANAGER_BRAND_SERIES = "update_manager_brand_series"
APPLY_MANAGER_SERIES_GALLERY_TO_PRODUCTS = "apply_manager_series_gallery_to_products"
DELETE_MANAGER_BRAND_SERIES = "delete_manager_brand_series"
LIST_MANAGER_FEATURE_CATEGORIES = "list_manager_feature_categories"
LIST_MANAGER_FEATURES = "list_manager_features"
CREATE_MANAGER_FEATURE = "create_manager_feature"
GET_MANAGER_FEATURE = "get_manager_feature"
UPDATE_MANAGER_FEATURE = "update_manager_feature"
ARCHIVE_MANAGER_FEATURE = "archive_manager_feature"
UPSERT_MANAGER_FEATURE_TARGET_LINK = "upsert_manager_feature_target_link"
DELETE_MANAGER_FEATURE_TARGET_LINK = "delete_manager_feature_target_link"
GET_MANAGER_PRODUCT_FEATURES = "get_manager_product_features"
UPDATE_MANAGER_PRODUCT_FEATURES = "update_manager_product_features"
DELETE_MANAGER_PRODUCT_FEATURE = "delete_manager_product_feature"
APPLY_MANAGER_PRODUCT_FEATURE_SUGGESTIONS = "apply_manager_product_feature_suggestions"
LIST_MANAGER_PRODUCT_COLLECTIONS = "list_manager_product_collections"
CREATE_MANAGER_PRODUCT_COLLECTION = "create_manager_product_collection"
GET_MANAGER_PRODUCT_COLLECTION = "get_manager_product_collection"
UPDATE_MANAGER_PRODUCT_COLLECTION = "update_manager_product_collection"
DUPLICATE_MANAGER_PRODUCT_COLLECTION = "duplicate_manager_product_collection"
ARCHIVE_MANAGER_PRODUCT_COLLECTION = "archive_manager_product_collection"
REPLACE_MANAGER_PRODUCT_COLLECTION_ITEMS = "replace_manager_product_collection_items"
REPLACE_MANAGER_PRODUCT_COLLECTION_PLACEMENTS = "replace_manager_product_collection_placements"
PREVIEW_MANAGER_PRODUCT_COLLECTION = "preview_manager_product_collection"
GET_MANAGER_PRODUCT_COLLECTION_RULE_OPTIONS = "get_manager_product_collection_rule_options"
LIST_MANAGER_TENANT_OFFERS = "list_manager_tenant_offers"
UPSERT_MANAGER_TENANT_OFFER = "upsert_manager_tenant_offer"
GET_MANAGER_TENANT_OFFER = "get_manager_tenant_offer"
UPDATE_MANAGER_TENANT_OFFER = "update_manager_tenant_offer"
LIST_MANAGER_TENANT_AUDIT_EVENTS = "list_manager_tenant_audit_events"
LIST_SUPPLIERS = "list_suppliers"
CREATE_SUPPLIER = "create_supplier"
PATCH_SUPPLIER = "patch_supplier"
DELETE_SUPPLIER = "delete_supplier"
LIST_SUPPLIER_CONTACTS = "list_supplier_contacts"
CREATE_SUPPLIER_CONTACT = "create_supplier_contact"
PATCH_SUPPLIER_CONTACT = "patch_supplier_contact"
DELETE_SUPPLIER_CONTACT = "delete_supplier_contact"
LIST_SUPPLIER_WAREHOUSES = "list_supplier_warehouses"
CREATE_SUPPLIER_WAREHOUSE = "create_supplier_warehouse"
PATCH_SUPPLIER_WAREHOUSE = "patch_supplier_warehouse"
DELETE_SUPPLIER_WAREHOUSE = "delete_supplier_warehouse"
LIST_SUPPLIER_SOURCES = "list_supplier_sources"
CREATE_SUPPLIER_SOURCE = "create_supplier_source"
PATCH_SUPPLIER_SOURCE = "patch_supplier_source"
DELETE_SUPPLIER_SOURCE = "delete_supplier_source"
ANALYZE_SUPPLIER_SOURCE = "analyze_supplier_source"
SYNC_SUPPLIER_SOURCE = "sync_supplier_source"
LIST_UNMAPPED_SUPPLIER_OFFERS = "list_unmapped_supplier_offers"
LIST_SUPPLIER_SOURCE_URL_IMPORT_CANDIDATES = "list_supplier_source_url_import_candidates"
START_SUPPLIER_SOURCE_URL_IMPORT = "start_supplier_source_url_import"
CREATE_SUPPLIER_MAPPING = "create_supplier_mapping"
DELETE_SUPPLIER_MAPPING = "delete_supplier_mapping"
GET_PRODUCT_SUPPLIER_OFFERS = "get_product_supplier_offers"
UPSERT_PRODUCT_LOCAL_STOCK = "upsert_product_local_stock"
LIST_SUPPLIER_SHEETS = "list_supplier_sheets"
SYNC_ALL_SUPPLIER_SOURCES = "sync_all_supplier_sources"
SUGGEST_SUPPLIER_OFFERS = "suggest_supplier_offers"
BULK_CREATE_SUPPLIER_MAPPINGS = "bulk_create_supplier_mappings"
LIST_SUPPLY_REQUESTS = "list_supply_requests"
CREATE_SUPPLY_REQUEST = "create_supply_request"
CREATE_SUPPLY_REQUEST_FROM_ORDER_LINES = "create_supply_request_from_order_lines"
CREATE_STOCK_SUPPLY_REQUEST = "create_stock_supply_request"
PATCH_SUPPLY_REQUEST = "patch_supply_request"
PATCH_SUPPLY_REQUEST_LINE = "patch_supply_request_line"
GENERATE_SUPPLY_REQUEST_SUPPLIER_MESSAGE = "generate_supply_request_supplier_message"
GENERATE_SUPPLY_LOGISTICS_MESSAGE = "generate_supply_logistics_message"

ALL_MANAGER_OPERATION_IDS = (
    READ_USER_ME,
    GET_MANAGER_CALENDAR_EVENTS,
    GET_MANAGER_PRODUCTS,
    GET_MANAGER_PRODUCT,
    GET_MANAGER_CATALOG_QUALITY_REPORT,
    GET_MANAGER_CUSTOMERS,
    GET_MANAGER_CUSTOMER_DETAIL,
    GET_MANAGER_CUSTOMER_DOCS,
    GET_MANAGER_CUSTOMER_RECONCILIATION,
    CREATE_MANAGER_CUSTOMER_RECONCILIATION_DOCUMENT,
    RECOGNIZE_MANAGER_CUSTOMER_REQUISITES,
    CONFIRM_MANAGER_CUSTOMER_REQUISITES,
    GET_MANAGER_CUSTOMER_BRANCHES,
    CREATE_MANAGER_CUSTOMER_BRANCH,
    PATCH_MANAGER_CUSTOMER_BRANCH,
    DELETE_MANAGER_CUSTOMER_BRANCH,
    LIST_MANAGER_EQUIPMENT,
    CREATE_MANAGER_EQUIPMENT,
    CREATE_MANAGER_EQUIPMENT_FROM_ORDER,
    CREATE_MANAGER_MAINTENANCE_ORDER,
    GET_MANAGER_EQUIPMENT,
    PATCH_MANAGER_EQUIPMENT,
    CREATE_MANAGER_EQUIPMENT_COMPONENT,
    PATCH_MANAGER_EQUIPMENT_COMPONENT,
    LIST_MANAGER_EQUIPMENT_HISTORY,
    CREATE_MANAGER_EQUIPMENT_HISTORY,
    CREATE_MANAGER_EQUIPMENT_HISTORY_FROM_REPAIR_ORDER,
    LIST_MANAGER_ORDER_ATTACHMENTS,
    LIST_MANAGER_EQUIPMENT_ATTACHMENTS,
    UPLOAD_MANAGER_ORDER_ATTACHMENT,
    PATCH_MANAGER_SERVICE_ATTACHMENT,
    DELETE_MANAGER_SERVICE_ATTACHMENT,
    GET_MANAGER_SERVICE_ATTACHMENT_ACCESS,
    LIST_MANAGER_ORDER_EQUIPMENT_LINKS,
    CREATE_MANAGER_ORDER_EQUIPMENT_LINK,
    DELETE_MANAGER_ORDER_EQUIPMENT_LINK,
    LIST_MANAGER_WARRANTY_POLICIES,
    CREATE_MANAGER_WARRANTY_POLICY,
    PATCH_MANAGER_WARRANTY_POLICY,
    LIST_MANAGER_EQUIPMENT_WARRANTY_COVERAGES,
    DECIDE_MANAGER_WARRANTY_COVERAGE,
    GET_MANAGER_CUSTOMER_CONTRACTS,
    CREATE_MANAGER_CUSTOMER_CONTRACT,
    UPLOAD_MANAGER_CUSTOMER_CONTRACT,
    PATCH_MANAGER_CUSTOMER_CONTRACT,
    ARCHIVE_MANAGER_CUSTOMER_CONTRACT,
    DELETE_MANAGER_CUSTOMER_CONTRACT,
    PATCH_MANAGER_CUSTOMER,
    DELETE_MANAGER_CUSTOMER,
    CREATE_MANAGER_PRODUCT,
    DUPLICATE_MANAGER_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_MANAGER_PRODUCT,
    BULK_ROUND_PRICE,
    BULK_SET_RRC_PRICE,
    BULK_DELETE_MANAGER_PRODUCTS,
    GET_ALL_TAGS,
    SMART_SEARCH_PRODUCTS,
    GET_MANAGER_YANDEX_BUSINESS_PRICE_LIST,
    GET_MANAGER_YANDEX_BUSINESS_QUALITY_REPORT,
    BULK_UPDATE_SPECS,
    NORMALIZE_LEGACY_SPECS,
    SEARCH_IMAGES,
    UPLOAD_IMAGE,
    UPLOAD_LOCAL_IMAGES,
    REUSE_SEARCH,
    GET_COMMON_GALLERY_IMAGES,
    LINK_SEARCH_RESULT,
    SET_MAIN_IMAGE,
    DELETE_IMAGE,
    CROP_PRODUCT_IMAGE,
    REMOVE_PRODUCT_IMAGE_BACKGROUND,
    REUSE_IMAGE,
    BULK_ADD_GALLERY_IMAGES,
    BULK_UPLOAD_LOCAL_IMAGES,
    BULK_DELETE_COMMON_GALLERY_IMAGES,
    APPLY_GALLERY_TO_SERIES,
    CLEANUP_MEDIA,
    GET_IMAGE_VARIANT_CANDIDATES,
    PROCESS_MISSING_IMAGE_VARIANTS,
    REPROCESS_IMAGE_VARIANT,
    LIST_MEDIA_ASSETS,
    GET_MEDIA_BACKGROUND_REMOVAL_CONFIG,
    UPLOAD_MEDIA_ASSETS,
    UPLOAD_MEDIA_ASSET_FROM_URL,
    BACKFILL_REFERENCED_MEDIA_ASSETS,
    UPDATE_MEDIA_ASSET,
    DELETE_MEDIA_ASSET,
    CROP_MEDIA_ASSET,
    REMOVE_MEDIA_ASSET_BACKGROUND,
    CREATE_MEDIA_PROCESSING_JOB,
    LIST_MEDIA_PROCESSING_JOBS,
    CLAIM_MEDIA_WORKER_JOB,
    RENEW_MEDIA_WORKER_JOB,
    COMPLETE_MEDIA_WORKER_JOB,
    FAIL_MEDIA_WORKER_JOB,
    CREATE_MAIN_IMAGE_CLEANUP_BATCH,
    LIST_MAIN_IMAGE_CLEANUP_BATCHES,
    LIST_MAIN_IMAGE_CLEANUP_ITEMS,
    APPROVE_MAIN_IMAGE_CLEANUP_ITEMS,
    REJECT_MAIN_IMAGE_CLEANUP_ITEMS,
    SKIP_MAIN_IMAGE_CLEANUP_ITEMS,
    LIST_MAIN_IMAGE_CLEANUP_SKIP_REASONS,
    GET_MANAGER_LEADS,
    CREATE_MANAGER_LEAD,
    PATCH_MANAGER_LEAD,
    QUALIFY_MANAGER_LEAD,
    MARK_MANAGER_LEAD_LOST,
    GET_MANAGER_LEADS_COUNTER,
    GET_MANAGER_LEADS_INBOX,
    GET_MANAGER_ORDERS,
    CREATE_MANAGER_ORDER,
    EXPORT_MANAGER_ORDERS,
    PREVIEW_IMPORT_MANAGER_ORDERS,
    IMPORT_MANAGER_ORDERS,
    GET_MANAGER_ORDER_DETAIL,
    PATCH_MANAGER_ORDER,
    DELETE_MANAGER_ORDER,
    CREATE_MANAGER_ORDER_PROPOSAL,
    DUPLICATE_MANAGER_ORDER_PROPOSAL,
    PATCH_MANAGER_ORDER_PROPOSAL,
    ARCHIVE_MANAGER_ORDER_PROPOSAL,
    SELECT_MANAGER_ORDER_PROPOSAL,
    GENERATE_MANAGER_ORDER_DOCUMENT,
    UPLOAD_MANAGER_ORDER_DOCUMENT,
    REGISTER_MANAGER_EXTERNAL_CONTRACT,
    GET_MANAGER_ORDER_DOCUMENTS,
    ATTACH_MANAGER_DOC_FILE,
    ADD_MANAGER_ORDER_PAYMENT,
    DELETE_MANAGER_ORDER_PAYMENT,
    CREATE_MANAGER_ORDER_STAGE,
    UPDATE_MANAGER_ORDER_STAGE,
    DELETE_MANAGER_ORDER_STAGE,
    LIST_MANAGER_STALE_ORDER_STAGES,
    CANCEL_MANAGER_ORDER_STAGE_DIRECT,
    DELETE_MANAGER_ORDER_STAGE_DIRECT,
    GET_MANAGER_DOC_DOWNLOAD,
    DELETE_MANAGER_DOC,
    IMPORT_MANAGER_BANK_RECEIPTS,
    IMPORT_MANAGER_BANK_STATEMENT,
    IMPORT_MANAGER_EMAIL_LEADS,
    GET_MANAGER_EMAIL_LEAD_IMPORT_STATUS,
    LIST_MANAGER_BANK_RECEIPTS,
    ATTACH_MANAGER_BANK_RECEIPT,
    ATTACH_MANAGER_BANK_RECEIPT_GROUP,
    GET_MANAGER_BANK_RECEIPT_ALLOCATION,
    REPLACE_MANAGER_BANK_RECEIPT_ALLOCATIONS,
    PATCH_MANAGER_BANK_RECEIPT_STATUS,
    DELETE_MANAGER_BANK_RECEIPT,
    LIST_MANAGER_OUTGOING_EMAILS,
    GET_MANAGER_OUTGOING_EMAIL,
    LIST_MANAGER_ORDER_OUTGOING_EMAILS,
    RETRY_MANAGER_OUTGOING_EMAIL,
    SEND_MANAGER_TEST_EMAIL,
    COMPOSE_MANAGER_ORDER_EMAIL,
    SEND_MANAGER_ORDER_EMAIL,
    LIST_MANAGER_DOCUMENT_TEMPLATES,
    LIST_MANAGER_DOCUMENT_TEMPLATE_FILES,
    CREATE_MANAGER_DOCUMENT_TEMPLATE,
    PATCH_MANAGER_DOCUMENT_TEMPLATE,
    DELETE_MANAGER_DOCUMENT_TEMPLATE,
    GET_MANAGER_CRM_HEALTH_REPORT,
    GET_DASHBOARD_STATS,
    IMPORT_ONLINER,
    GET_MANAGER_INSTALLERS,
    CREATE_MANAGER_INSTALLER,
    UPDATE_MANAGER_INSTALLER,
    SEARCH_MANAGER_INSTALLERS,
    LIST_MANAGER_STAFF,
    CREATE_MANAGER_STAFF,
    PATCH_MANAGER_STAFF,
    LIST_MANAGER_SETTINGS,
    CREATE_MANAGER_SETTING,
    GET_FX_RATE,
    SUGGEST_ADDRESS,
    UPDATE_MANAGER_SETTING,
    GET_MANAGER_GOOGLE_AUTH_STATUS,
    GET_MANAGER_GOOGLE_AUTH_URL,
    LIST_MANAGER_BACKUPS,
    START_MANAGER_BACKUP_RUN,
    GET_MANAGER_BACKUP_RUN_STATUS,
    START_MANAGER_BACKUP_RESTORE,
    GET_MANAGER_BACKUP_RESTORE_STATUS,
    LIST_MANAGER_TARIFFS,
    LIST_MANAGER_QUICK_TARIFFS,
    CREATE_MANAGER_TARIFF,
    UPDATE_MANAGER_TARIFF,
    DELETE_MANAGER_TARIFF,
    LIST_MANAGER_TARIFF_RULES,
    LIST_MANAGER_FAVORITE_TARIFF_RULES,
    CREATE_MANAGER_TARIFF_RULE,
    UPDATE_MANAGER_TARIFF_RULE,
    DELETE_MANAGER_TARIFF_RULE,
    LIST_MANAGER_REPAIR_COMPLAINT_PRESETS,
    CREATE_MANAGER_REPAIR_COMPLAINT_PRESET,
    UPDATE_MANAGER_REPAIR_COMPLAINT_PRESET,
    DELETE_MANAGER_REPAIR_COMPLAINT_PRESET,
    GENERATE_MANAGER_REPAIR_ACT_AI_DRAFT,
    CALCULATE_MANAGER_INSTALL_ESTIMATE,
    CREATE_MANAGER_SERVICE_ESTIMATE,
    LIST_MANAGER_SERVICE_ESTIMATES,
    GET_MANAGER_SERVICE_ESTIMATE,
    DELETE_MANAGER_SERVICE_ESTIMATE,
    GET_MANAGER_SERVICE_ESTIMATE_ORDER_LINES,
    GET_MANAGER_TAG_GROUPS,
    CREATE_MANAGER_TAG_GROUP,
    UPDATE_MANAGER_TAG_GROUP,
    DELETE_MANAGER_TAG_GROUP,
    CREATE_MANAGER_TAG,
    UPDATE_MANAGER_TAG,
    DELETE_MANAGER_TAG,
    LIST_MANAGER_BRANDS,
    CREATE_MANAGER_BRAND,
    UPDATE_MANAGER_BRAND,
    DELETE_MANAGER_BRAND,
    LIST_MANAGER_BRAND_FEATURES,
    CREATE_MANAGER_BRAND_FEATURE,
    UPDATE_MANAGER_BRAND_FEATURE,
    DELETE_MANAGER_BRAND_FEATURE,
    LIST_MANAGER_BRAND_SERIES,
    CREATE_MANAGER_BRAND_SERIES,
    UPDATE_MANAGER_BRAND_SERIES,
    APPLY_MANAGER_SERIES_GALLERY_TO_PRODUCTS,
    DELETE_MANAGER_BRAND_SERIES,
    LIST_MANAGER_FEATURE_CATEGORIES,
    LIST_MANAGER_FEATURES,
    CREATE_MANAGER_FEATURE,
    GET_MANAGER_FEATURE,
    UPDATE_MANAGER_FEATURE,
    ARCHIVE_MANAGER_FEATURE,
    UPSERT_MANAGER_FEATURE_TARGET_LINK,
    DELETE_MANAGER_FEATURE_TARGET_LINK,
    GET_MANAGER_PRODUCT_FEATURES,
    UPDATE_MANAGER_PRODUCT_FEATURES,
    DELETE_MANAGER_PRODUCT_FEATURE,
    APPLY_MANAGER_PRODUCT_FEATURE_SUGGESTIONS,
    LIST_MANAGER_PRODUCT_COLLECTIONS,
    CREATE_MANAGER_PRODUCT_COLLECTION,
    GET_MANAGER_PRODUCT_COLLECTION,
    UPDATE_MANAGER_PRODUCT_COLLECTION,
    DUPLICATE_MANAGER_PRODUCT_COLLECTION,
    ARCHIVE_MANAGER_PRODUCT_COLLECTION,
    REPLACE_MANAGER_PRODUCT_COLLECTION_ITEMS,
    REPLACE_MANAGER_PRODUCT_COLLECTION_PLACEMENTS,
    PREVIEW_MANAGER_PRODUCT_COLLECTION,
    GET_MANAGER_PRODUCT_COLLECTION_RULE_OPTIONS,
    LIST_MANAGER_TENANT_OFFERS,
    UPSERT_MANAGER_TENANT_OFFER,
    GET_MANAGER_TENANT_OFFER,
    UPDATE_MANAGER_TENANT_OFFER,
    LIST_MANAGER_TENANT_AUDIT_EVENTS,
    LIST_SUPPLIERS,
    CREATE_SUPPLIER,
    PATCH_SUPPLIER,
    DELETE_SUPPLIER,
    LIST_SUPPLIER_CONTACTS,
    CREATE_SUPPLIER_CONTACT,
    PATCH_SUPPLIER_CONTACT,
    DELETE_SUPPLIER_CONTACT,
    LIST_SUPPLIER_WAREHOUSES,
    CREATE_SUPPLIER_WAREHOUSE,
    PATCH_SUPPLIER_WAREHOUSE,
    DELETE_SUPPLIER_WAREHOUSE,
    LIST_SUPPLIER_SOURCES,
    CREATE_SUPPLIER_SOURCE,
    PATCH_SUPPLIER_SOURCE,
    DELETE_SUPPLIER_SOURCE,
    ANALYZE_SUPPLIER_SOURCE,
    SYNC_SUPPLIER_SOURCE,
    LIST_UNMAPPED_SUPPLIER_OFFERS,
    LIST_SUPPLIER_SOURCE_URL_IMPORT_CANDIDATES,
    START_SUPPLIER_SOURCE_URL_IMPORT,
    CREATE_SUPPLIER_MAPPING,
    DELETE_SUPPLIER_MAPPING,
    GET_PRODUCT_SUPPLIER_OFFERS,
    UPSERT_PRODUCT_LOCAL_STOCK,
    LIST_SUPPLIER_SHEETS,
    SYNC_ALL_SUPPLIER_SOURCES,
    SUGGEST_SUPPLIER_OFFERS,
    BULK_CREATE_SUPPLIER_MAPPINGS,
    LIST_SUPPLY_REQUESTS,
    CREATE_SUPPLY_REQUEST,
    CREATE_SUPPLY_REQUEST_FROM_ORDER_LINES,
    CREATE_STOCK_SUPPLY_REQUEST,
    PATCH_SUPPLY_REQUEST,
    PATCH_SUPPLY_REQUEST_LINE,
    GENERATE_SUPPLY_REQUEST_SUPPLIER_MESSAGE,
    GENERATE_SUPPLY_LOGISTICS_MESSAGE,
    GET_DOC_TEMPLATES,
    CATALOG_IMPORT,
    PREVIEW_MDV_CATALOG_IMPORT,
    START_CATALOG_IMPORT_JOB,
    START_MDV_CATALOG_IMPORT_JOB,
    GET_CATALOG_IMPORT_JOB_STATUS,
    GET_CURRENT_CATALOG_IMPORT_JOB_STATUS,
)
